#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Outline
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/outline.org
  :Created: 2017-02-04T22:55@Prek Leap (11.642600N-104.919210W)
  :ID: 1f659b6c-3d5c-4515-89a3-63f1667966fe
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction



* THE TRIVIUM


Throughout the Middle Ages, formal education began with the study of
language: grammar, including the study of literature as well as the
practical mastery of the mechanics of language (here, Latin); logic or
dialectic, whether narrowly defined as the art of constructing arguments
or, more generally, as metaphysics, including the philosophy of mind;
and rhetoric, or the art of speaking well, whether to praise or
persuade.
 

/Martianus Capella and the Seven Liberal Arts: Vol. II  The Marriage of
Mercury and Philology/, trans. William Harris Stahl with E.L. Budge (New
York: Columbia University Press, 1992).

John of Salisbury, /The Metalogicon: A Twelfth-Century Defense of the
Verbal and Logical Arts of the Trivium/, trans. Daniel D. McGarry
(Philadelphia: Paul Dry Books, 2009).

 

All other readings available online through JSTOR, Google Books, or
Chalk.   Readings marked “Reg” are also on reserve at the Regenstein
Library.


** Why study the /trivium/?

Dorothy Sayers, [[http://www.gbt.org/text/sayers.html][The Lost Tools of Learning]] (1947)

** Education in the Middle Ages

Lynn Thorndike, “Elementary and Secondary Education in the Middle Ages,”
/Speculum/ 15.4 (October 1940): 400-408 [JSTOR]

Caroline M. Barron, “The Expansion of Education in Fifteenth-Century
London,” in /The Cloister and the World: Essays in Medieval History in
Honour of Barbara Harvey/, eds. John Blair and Brian Golding (Oxford:
Clarendon Press, 1996), pp. 219-45 [Chalk]

 

Charles H. Haskins, “A List of Text-Books from the Close of the Twelfth
Century,” /Harvard Studies in Classical Philology/ 20 (1909): 75-94 [JSTOR]

Alexander Nequam, A list of textbooks from /Sacerdos ad altare/, in
/Medieval Grammar and Rhetoric: Language Arts and Literary Theory, AD
300-1475/, eds. Rita Copeland and Ineke Sluiter (Oxford: Oxford
University Press, 2009), pp. 531-41 [Chalk; Reg]

 “Appendix I: A Time-Table of Lectures in the Arts Course of the
University of Toulouse, 1309,” in Louis John Paetow, /The Arts Course at
Medieval Universities with Special Reference to Grammar and Rhetoric/
(Champaign, IL: 1910), pp. 95-99 [Google Books]

** January 10 The Seven Liberal Arts

Honorius Augustodunensis, “Concerning the Exile of the Soul and its
Fatherland; also called, About the Arts,” in /Readings in Medieval
Rhetoric/, ed. Joseph M. Miller, Michael H. Prosser, and Thomas W.
Benson (Bloomington: Indiana University Press, 1973), pp. 198-206
[Chalk; Reg]

Henri d’Andeli, “The Battle of the Seven Arts,” ed. and trans. Louis
John Paetow, /Memoirs of the University of California/ 4.1, /History/
1.1 (Berkeley: University of California Press, 1914), pp. 37-60 [Chalk]

 

H. Parker, “The Seven Liberal Arts,” /The English Historical Review/
5.19 (Jul. 1890): 417-61 [JSTOR]

Karl F. Morrison, “Incentives for Studying the Liberal Arts,” in /The
Seven Liberal Arts in the Middle Ages/, ed. David L. Wagner
(Bloomington: Indiana University Press, 1983), pp. 32-57 [Chalk; Reg]

 

** The Nuptials of Eloquence and Learning

Martianus Capella, /The Marriage of Mercury and Philology/, bks. I-II,
trans. Stahl, pp. 3-63 [Sem Co-op; Reg]

 

W.H. Stahl, “To a Better Understanding of Martianus Capella,” /Speculum
/40.1 (Jan. 1940): 102-115 [JSTOR]

Cora Lutz, “Remigius’ Ideas on the Origin of the Seven Liberal Arts,”
/Medievalia et Humanistica/ 10 (1956): 32-49 [Chalk]

Cora Lutz, “Remigius’ Ideas on the Classification of the Seven Liberal
Arts,” /Traditio/ 12 (1956): 65-86 [JSTOR]

 

* I. GRAMMAR

 

** What did Grammar teach?

Martianus Capella, /Marriage/, bk. III, trans. Stahl, pp. 64-105.

Cassiodorus, /Institutions of Divine and Secular Learning/, bk. II,
preface, trans. James W. Halporn (Liverpool: Liverpool University Press,
2004), pp. 171-78 [Chalk]

Jeffrey F. Huntsman, “Grammar,” in /The Seven Liberal Arts/, ed. Wagner,
pp. 58-95 [Chalk; Reg]

** /Ars grammatica antiqua/

Aelius Donatus, /Ars Minor/, /Ars Maior/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 82-99 [Chalk; Reg]

Priscian, /Institutiones Grammaticae/ and /Institutio de Nomine
Pronomine Verbo/, in /Medieval Grammar and Rhetoric/, eds. Copeland and
Sluiter, pp. 167-89 [Chalk; Reg]

Isidore of Seville, /Etymologiae/, in /Medieval Grammar and Rhetoric/,
eds. Copeland and Sluiter, pp. 232-41 [Chalk; Reg]

Alcuin, /Ars Grammatica/, in /Medieval Grammar and Rhetoric/, eds.
Copeland and Sluiter, pp. 272-87 [Chalk; Reg]

Glosses on Priscian by Remigius and His Followers, in /Medieval Grammar
and Rhetoric/, eds. Copeland and Sluiter, pp. 299-310 [Chalk; Reg]


** Reading the classics

/Accessus ad auctores/[Introductions to the Authors], in /Medieval
Literary Theory and Criticism, c. 1100-c.1375: The Commentary
Tradition/, eds. A.J. Minnis and A.B. Scott, with David Wallace, rev.
ed. (Oxford: Clarendon Press, 1988), pp. 12-36 [Chalk]

Conrad of Hirsau, “Dialogue on the Authors,” in /Medieval Literary
Theory/, eds. Minnis and Scott, pp. 37-64 [Chalk]

 

** Thinking grammatically

Anselm of Canterbury, /De grammatico/, in /The Major Works/, eds. Brian
Davies and G.R. Evans (Oxford: Oxford University Press, 1998), pp.
123-50 [Chalk]

John of Salisbury, /Metalogicon/, bk. I, chaps. 13-25, trans. McGarry,
pp. 37-72 [Sem Co-op; Reg]

 

** /Ars grammatica nova/

Alexander of Villa Dei, /Doctrinale/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 573-83 [Chalk; Reg]

Eberhard of Béthune, /Graecismus/, in /Medieval Grammar and Rhetoric/,
eds. Copeland and Sluiter, pp. 584-93 [Chalk; Reg]

 

James J. Murphy, “The Teaching of Latin as a Second Language in the
Twelfth Century,” in /Latin Rhetoric and Education in the Middle Ages
and Renaissance /(Aldershot: Ashgate/Variorum, 2005), III [Chalk]

Robert Black, “The Vernacular and the Teaching of Latin in Thirteenth
and Fourteenth-Century Italy,” /Studi Medievali/, 3^rd ser. 37 (1996):
703-51 [Chalk]

Nicholas Orme, “John Holt (d. 1504), Tudor Schoolmaster and Grammarian,”
/The Library/, 6^th ser. 18.4 (December 1996): 283-304 [Chalk]

 
* II. DIALECTIC

** What did Dialectic teach?

Martianus Capella, /Marriage/, bk. IV, trans. Stahl, pp. 106-154

Cassiodorus, /Institutions/, bk. II, chap. III, trans. Halporn, pp.
188-208 [Chalk]

 
Eleanore Stump, “Dialectic,” in /The Seven Liberal Arts/, ed. Wagner,
pp. 125-46 [Chalk; Reg]

 

** The Problem with Education These Days

John of Salisbury, /Metalogicon/, Prologue; bk. I, chaps. 1-12; bk. II,
chaps. 1-20; trans. McGarry, pp. 3-37, 73-141

 

** The Point of It All

John of Salisbury, /Metalogicon/, bks. III-IV, trans. McGarry, pp. 142-276

 

** Applied Dialectic: Universals and Particulars

Aristotle, Porphyry, Boethius, Garlandus Compotista, and Abelard, in
/Basic Issues in Medieval Philosophy/, eds. Bosley and Tweedale, Topic
VI, pp. 352-92 [Chalk]

John of Salisbury, /Metalogicon/, bk. II, chaps. 17-20; bk. III, chaps.
1-4; trans. McGarry, pp. 111-41, 146-70

* III. RHETORIC


** What did Rhetoric teach?

Martianus Capella, /Marriage/, bk. V, trans. Stahl, pp. 155-214

Cassiodorus, /Institutions/, bk. II, chap. II, trans. Halporn, pp.
178-88 [Chalk]


Martin Camargo, “Rhetoric,” in /The Seven Liberal Arts/, ed. Wagner, pp.
96-124 [Chalk]

 

** /Rhetorica christiana/

Augustine of Hippo, /On Christian Doctrine/, bk. IV, trans. J.F. Shaw,
pp. 154-203 [CCEL http://www.ccel.org/a/augustine/doctrine/]

Bede, /De schematibus et tropis/ [“Concerning Figures and Tropes”],
trans. Gussie Hecht Tannenhaus, in /Readings in Medieval Rhetoric/, eds.
Miller et al., pp. 96-122 [Chalk; Reg]

 
** /Ars poetica/

Matthew of Vendôme, /Ars versificatoria/ [/The Art of Versification/],
trans. Aubrey E. Galyon (Ames: Iowa State University Press, 1980), pp.
25-112 [Chalk]

Geoffrey of Vinsauf, /Poetria nova/, trans. Margaret F. Nims (Toronto:
Pontifical Institute of Mediaeval Studies, 1967), pp. 15-93 [Chalk]

** /Ars dictaminis/

John of Garland, /Parisiana poetria/, ed. and trans. Traugott Lawler
(New Haven: Yale University Press, 1974), chaps. 1-4, 7, pp. 3-83,
143-59 (odd numbered pages) [Chalk]

Anonymous of Bologna, /Rationes dictandi/ [/The Principles of
Letter-Writing/], trans. James J. Murphy, in /Three Medieval Rhetorical
Arts/, ed. James J. Murphy (Berkeley and Los Angeles: University of
California Press, 1971), pp. 3-25 [Chalk; Reg]


** /Ars praedicandi/

Thomas of Chobham, /Summa de arte praedicandi/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 614-38 [Chalk; Reg]

Robert of Basevorn, /Forma praedicandi/ [/The Form of Preaching/],
trans. Leopold Krul, O.S.B., in /Three Medieval Rhetorical Arts/, ed.
Murphy, pp. 111-215 [Chalk; Reg]


 

