#   -*- mode: org; fill-column: 60 -*-

#+TITLE: Introduction | Quadrivium
#+STARTUP: showall
#+TOC: headlines 4
#+PROPERTY: filename

[[https://img.shields.io/badge/made%20by-Chenla%20Institute-999999.svg?style=flat-square]] 
[[https://img.shields.io/badge/class-primer-56B4E9.svg?style=flat-square]]
[[https://img.shields.io/badge/type-work-0072B2.svg?style=flat-square]]
[[https://img.shields.io/badge/status-wip-D55E00.svg?style=flat-square]]
[[https://img.shields.io/badge/licence-MIT%2FCC%20BY--SA%204.0-000000.svg?style=flat-square]]

* Introduction | Quadrivium
:PROPERTIES:
:CUSTOM_ID: 
:Name:      /home/deerpig/proj/chenla/trivium/quad-introduction.org
:Created:   2017-03-30T17:45@Prek Leap (11.642600N-104.919210W)
:ID:        aa32930a-3ee2-4420-b6b9-4f1987cca43c
:VER:       564188865.137237992
:GEO:       48P-491193-1287029-15
:BXID:      proj:NAU2-4815
:Class:     primer
:Type:      work
:Status:    wip
:Licence:   MIT/CC BY-SA 4.0
:END:



The original Quadrivium was made up of four subjects that each dealt
with different aspects of number and magnitude: arithmetic, geometry,
music and astronomy.  This originated with Plato's belief that the
Universe could best be understood in terms of number.

 - Quadrivium :: four arts of quantity pertaining to matter

  /discrete quantities/

   - arithmetic (theory of number)
     - algebra, calculus, etc
   - music (applied theory of number)
     - harmony, chemistry, 

   /continuous quantity/

   - geometry (theory of space)
     - geometry, trigonometry
   - astronomy (applied theory of space)
     - architecture, geography, surveying, engineering 


** Introduction

Our understanding of how the world works is far more complex
and nuanced today.  And even though in recent years the idea
that we live in a /mathematical universe/ has brought us
full circle back to Plato in some respects, mathematics is
still removed from physical reality and from mind.

Mathematics is very good at modeling the universe, but the
universe is better understood in terms of complexity and it's
opposite, entropy.  Entropy is relentless and inevitable.
Complexity is both exceptional and fragile.  Complexity
would not be possible without entropy and vice versa.

#+begin_quote
Information is always a measure of the decrease of
uncertainty at a receiver (or molecular machine).

            R = H(x) - Hy(x) 

-- [[https://schneider.ncifcrf.gov/information.is.not.uncertainty.html][Information Is Not Uncertainty]]
-- [[https://schneider.ncifcrf.gov/bionet.info-theory.faq.html#Information.Equal.Entropy][bionet.info-theory FAQ]]
#+end_quote

The new Quadrivium is made up of four subject that deal with
different aspects of information; mimesis, rhizomata,
systema and transacta.
 
The four arts pertain to information expressed as matter,
energy, space and time.


  - mimesis   :: theory of models/maps
       map and territory  

  - rhizomata :: theory of structures
       sets, lists, trees, graphs

  - systema   :: theory of holons
       dual nature of parts and wholes

  - transacta :: theory of processes 
       threads running through systems


Like the trivium, these are not subjects in the traditional
sense of the word.  Different aspects of traditional
subjects such as physics, chemistry, mathematics etc will
belong to each of the four arts.


*** Mimesis

Mimesis is concerned with the internal and externalised systems used
to represent reality.

This goes to to the heart of human cognition -- 

a theory is linguistic, a model is a non-linguistic realization of a
theory.

models can be linguistic, non-linguistic and physical.

**** Mathematics

Mathematics represents reality in terms of relationships between
descrete quantities.  For math to be able to model reality, reality
must:

  1. contain discrete/finite quantities;
  2. these quantities must be able to interact with each other.

Not all mathematical truths correspond to reality.

Mathematics is a good match with the human brain, which is a pattern
recognition machine.


**** Instantial Models and Analogy
**** Representational Models
***** Material Models :: Maps
***** Material Models :: Diagrams
***** Material Models :: Scale Models
**** Abstract Models
**** Hypothesis
**** Theoretical Models
**** Mathematical Models
**** Models of Data
**** Data

*** Rhizomata

Rhizomata is concerned with the structures that make up models and
maps.

 - holons
 - pace layers
 - rhizomes
 - data structures



*** Systema
*** Transacta

Transacta is concerned with the interactions between the
different parts of a system.

Humans in isolation as individuals cut off from other humans are
animals.  All human intelligence, and intellectual achievements have
only been possible because of our transactive nature.  Memory, problem
solving, and survival are all broken down into specializations in
large groups.  Even between two individuals, memory and skills are
divided between them.  Because of this transactional nature, humans
have evolved to be generalists which can adapt to a wide range of
environments and circumstances.  Humans are not specialists
biologically, there are only two variations, male and female, which
is an evolutionary mechanism for the species to biologically change
and improve over time.  

  - Homo Sapians :: species
  - Human        :: conscious-bearing, transactive individual
  - Humanity     :: 
  - Mankind      :: collective

Further, that we must embrace a larger concept of what we are that is
not limited to any one species, but to collectively include any
conscious-bearing individual which is part of the collective
transactive process of the group.  This includes other species, like
the domesticated dog, who has a transactive relationship with, and is
part of human society.  It may one day include machine intelligences.
Computational and storage systems already have a transactive
relationship with mankind -- as these systems become more autonomous
they may evolve consciousness and self awareness and be accepted into
human society as part of mankind.


Specialization is often talked of in terms of a 'division of labour'
but this is a narrow concept --

  - the amount of knowledge required to maintain and advanced complex
    societies is greater than the ability of any one individual to
    master.  knowledge has fractured into ever smaller and smaller
    specialties.  It is not enough to store this information in books
    it must be maintained to some extent in living memory by people
    who actively apply that knowledge -- otherwise it has been lost to
    living memory and must be relearned, and partially reinvented as
    the skill sets that are lost are reinvented and developed anew.
  - the number of skilled tasks (jobs) that are required to maintain
    and advance a complex society is greater than 
  - technology and knowledge advance over time by many individuals,
    over many generations, it is an iterative process that would be
    impossible unless each advance is added to the collective commons
    and then built on -- standing on the shoulders of giants, as
    Newton said.
  - transactive memory is when memory is divided between two or more
    members of a group.
  - transactive senses is when the senses are divided between
    different individuals or even animals.....
