#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Logic
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-logic.org
  :Created: 2017-03-11T21:31@Prek Leap (11.642600N-104.919210W)
  :ID: ff5e852a-bcbb-48e2-a4b2-dbf678f24fbe
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

#+begin_quote
To appreciate the form and content of these debates, it is
convenient to start with the so-called /trivium/, the triad
of topics -- grammar, dialectic and rhetoric -- that served
at the lower tier of the Seven Liberal Arts.  These
categories, personified  as the deven daughters of
philosophy, comprised 'the rational endeavours of man'
(Katzenellenbogen, 1966, pp.47 &.39). To become rational
beings, learners should acquire such knowledge.  In
discussions of the trivium, dialectic is sometimes given an
alternative label -- logic; as indicated in the remainder of
this paper, medieval logic was not the same as the humanist
dialectic.

*Knowledge and Communication*

The Liberal Arts comprised yesterdays learning that was to
be learned by tomorrow's male adults.  The Liberal Arts were
self-referential.  They were both structured bodies of
knowledge and structured instruments for the communication
of knowledge.  To learn /from/ previous knowledge was also
to learn /through/ previous knowledge.  At the same time,
however, the structure of the Liberal Arts was ill-defined.
They were fluid rather than fixed bodies of knowledge and,
as a result their form as communication media was equally
imprecise.  They were more texts than textbooks.

The same argument applies to the trivium.  It is more easily
understood as an amorphous stage of learning than as a
henady set of tools for learning.  Collectively, grammar,
dialectic and rhetoric related to knowledge about -- and for
-- human communication.  Grammar was the chassis of
communcation, and dialectic and rhetoric comprised knowledge
about how the bodywork of communication should be moulded
and finished.  If knowledge and grammar fostered the ability
to write or speak Latin, dialectic and rhetoric underpinned
the capacity to produce Latin employed in the higher arts
(notably theology).  Further, the history of the trivium is
a history of how such 'good' Latin was characterised as a
body of knowledge to be learned, from and through.

Then, as now, learning a language was more than learning a
formal grammar.  It also included the appriciation of
vocabulary and word order.  To this extent, grammar spilled
over into the other elements of the Trivium.  If grammar
involved stringing words together, dialectic involved
stringing together propositions to make plausible (or
logical) arguments and rhetoric involved stringing words and
propositions together so an argument also became
persuasive.  Overall, the trivium embraced the strining of
words together to create arguments that were both plausible
(dialectic) and persuasive (rhetoric).

As suggested, the fortunes of the language arts waxed and
waned in the humanist-scholastic debate.  Medieval
scholasticism, for instance, was an expression of the
dominance of logic and, with it, the importance attached to
argumentation.  Attention to argumentation, reasoning, logic
and truth -- also known as aristotelian logic (because it
was based on certain texts attributed to Aristotle) -- had
been the core theological activity of the latter part of the
Middle Ages (1150-1450).

The search for logical rigour included attention to textual
deatil, identification of the shortcomings of earlier
commentators, invention of more precise terms and the
recalibration of earlier categories of thought.  Indeed,
much of the secondary historical literature on the trivium,
including the doctoral work of Walter Ong, has been taken up
with untangling the twists and turns of this s0-called
scholastic enterprise.

The language arts of the Renaissance -- 'Renaisance
argument' in Mack's terms -- arose from authors interested
in the power of persuasion as well as the logic of
argumentation.  They, too, focused on the use of language,
but, in the process, highlighted the impact of classical
prose and poetry on grammar and rhestoric.  Such early
humanists accepted the merits of dialectic (or logical
analysis), provided it was used as a basis for oratory, and
not as an end in itself.  The incursion of oratory, however,
prompted the claims of rhetoric.  Peter Mack succinctly
describe the link between rhetoric and oratory:

   The full course in rhetoric teaches many different
   skills, for example: how to think about an audience, how
   to begin and oration, how to relate a story, how to
   determine the main points at issue, how to devise and
   formulate arguments, in what order to place the parts of
   an oration, how to determine which style to employ and
   how to write it, how to conclude, how to deliver, and how
   to arouse the emotions of an audience. (1993, p.5).

Overall, the late middle Ages and the early Renaisance
supported innovators as well as formalists who, in their
different ways, derived 'all things from the ancients' (Ong,
1985,p.92).  The innovations of the humanists Lorenzo
Valla's work (e.g. /Rapastinatio dialecticae et
philosophiae/, 1439) focused on grammer as the foundation of
the trivium.  By grammar, however, Valla denoted a thorough
knowledge of both the language and the literature of ancient
Greek and Latin.  The acquistition of this language art was,
for Valla, 'fundemental' (Mack, 1993,p.96).

In effect, Valla reworked dialectic -- the word
/repastinatio/ can be interpreted as 'relaying', 'ploughing
in' or 'redigging' of the 'foundations of traditional logic'
(Rummel, 1995, p.156).  He called argumentation back from
the trickery of philisophical language and the disputation
of eternal truths. He redirected it back to natural
language, to the elegant organisation of phrases and
sentences, and to the practical purposes of persuation.  He
realigned it as a practical art whose form and content
should vary according to its context of use (e.g. court
room, senate chamber, burial ground).  He took elements from
grammar and its form from rhetoric.  Ancient texts provided
the raw material of argumentation; while rhetoric entailed
shaping the form and expression of arguments.  In the
proces, the perceived narrowness of Aristotelian logic was
displaced from humanist dialectic, debate and
argumentation.  As Mack suggested, the humanist view was
that 'where philosophical language obfuscates, rhetorical
language illuminates' (Mack, 1993, p.26).

Agricola's seminal work, /De inventione dialectica/ (1479),
came later.  It was a text which rethought 'the classical
heritage of persuasion in the light of a deep and careful
reading of Latin literature' (Mack 1993,p.120).  If Valla
had incorporated grammar and rhetoric into dialectic --
enlarging it in the process, Agricola completed his
predecessors work.  For Agricola, the language art of
dialectic entained speaking convincingly, 'according to the
situtation of the thing proposed' (Mack, 1993,0170).
Further, Agricola differentiated between speaking
convincingly and speaking clearly.  The latter was the
province of grammar -- finding appropriate words; whereas
dialectic embrased the organization of speech in particular
ways for for particular purposes.  Through this
distinction. Agricola forged a direct connection between
dialectic, teaching and another field beyond the purview of
this paper, preaching:

   When someone teaches in such a way that he wants to
   create belief through his speech, and to draw the mind of
   the hearer to him by what he says... he is dealing with
   the business of dialectic. (quoted in Mack, 1993, p.173).

There is a further important feature of Agricola's view of
dialectic.  As Onf noted, Agricola's dialectic was
'concerned more with how to deal with an audience than with
strict logical structure' (Ong, 1958,p.100).  In other
words, the psychology of teaching was as important as
assuring the logic of an argument.

Dialectic became the paradigmatic language art --
argumentation.  Gradually, however, something seemed to have
happened in the middle of the sixteenth century that changed
the face of education.  A gap opened up between teachings
and teaching.  As suggested earlier, to learn argumentaiton
was, somehow, to learn about teaching.  Argumentation,
therefor, could be appricieated as a mental, inside-the-head
activity (cf. thinking), or it could be thought of as an
external activity of speaking and writing (cf. debating).
Accordingly, dialectic acquired, Ong suggested, a 'curious
double-teaching charge' that was 'characteristic of Ramism':

   Like every other art, it is teaching (doctrina) by the
   very fact that it is an art (ars), but it is further the
   art or teaching of teaching' (Ong, 1958,p.161).

This view was typified in a later comment on Ramus'
proposals: 'speech teaches; reason learns; therefore
dialectic is the art of teaching and learning' (Johann
Piscator, quoted in Rummel, 1995,p.174; for further
discussion see Ong, 1958,p.161). Models of learning or
self-instruction became models for instruction.  A model for
aquiring knowledge (learning) became a model for
communicating knowledge (dialectic) and a model for
transmitting knowledge (instruction).  The language arts or
humanism were, in Ramist circles, transformed intto the
instructional arts of the humanities.

This-double-teaching charge -- or the translation of
teachings into teaching -- is also probed by the question:
who were the readers of /De inventione dialectica/?  Was it
written as a guide to self-study?  Was it prepared for
guided self-study (i.e. domestic tutoring)?  Or was it a
book to be placed unambiguously in the hands of school
keepers?  Again, Ong notes the fluidity of this issue,
insofar as. Agricola's text:

   might well be headed 'What Boys Should Know about
   Discourse' or, better, since it is addressed to teachers
   rather than pupils, 'Thoughts on Discourse and How to
   Teach It' (Ong 1968,p.100)

Printing houses were also sensitive to this problem, a
factor which underpinned the Ramist publishing triumph.
Ong, for instance, distinguishes the 'pupil-centered' stance
adopted by the humanists (whose texts were accommodated "to
real-life" and to the real pedagogical situation') from the
'teacher-oriented'[ attitude taken within the aristotelean,
lecturing milieux that survived in certain
universities. (Ong.1958,p 97)-- often those with links to
the philosophy of Thomas Aquinas.

-- [[bib:hamilton:2003instruction][Instruction in the Making]] | Hamilton
#+end_quote



* Dialectic Links

** What did Dialectic teach?

Martianus Capella, /Marriage/, bk. IV, trans. Stahl, pp. 106-154

Cassiodorus, /Institutions/, bk. II, chap. III, trans. Halporn, pp.
188-208 [Chalk]

 
Eleanore Stump, ﾒDialectic,ﾓ in /The Seven Liberal Arts/, ed. Wagner,
pp. 125-46 [Chalk; Reg]

 

** The Problem with Education These Days

John of Salisbury, /Metalogicon/, Prologue; bk. I, chaps. 1-12; bk. II,
chaps. 1-20; trans. McGarry, pp. 3-37, 73-141

 

** The Point of It All

John of Salisbury, /Metalogicon/, bks. III-IV, trans. McGarry, pp. 142-276

 

** Applied Dialectic: Universals and Particulars

Aristotle, Porphyry, Boethius, Garlandus Compotista, and Abelard, in
/Basic Issues in Medieval Philosophy/, eds. Bosley and Tweedale, Topic
VI, pp. 352-92 [Chalk]

John of Salisbury, /Metalogicon/, bk. II, chaps. 17-20; bk. III, chaps.
1-4; trans. McGarry, pp. 111-41, 146-70
