#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Mastery
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-mastery.org
  :Created: 2017-02-13T12:13@Prek Leap (11.642600N-104.919210W)
  :ID: 85b5b600-1212-475e-8aed-2ff90df670dc
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

I'm now going to break up mastery into four parts:

  - Mastery  :: Deals with the larger concepts of mastering a
                discipline and a basic philosophy of life
                work, learning and balance.
  - Practice :: The deliberate regular practice of anything
                that is one of the two pillars of work and
                learning.
  - Otium    :: The flip side of Practice which is
                deliberate, rest and contemplation.
  - Negotium :: Dealing with a person's public roles and
                interactions with people, family, collective
                projects, business, management roles etc.


It's only been very recently that Rest/Otium have started to
get any attention.  But we also need treat /negotium/ as
equally important in its own way.  Negotium  is our public
life, how we craft a persona that shapes how we are
percieved.  Interacting with the world is no mean feat.  And
for introverts and borderline recluses like my self, is an
enormous challenge.

---

Mastery is the process of lifelong learning.  The Trivium can be thought of
as a means of establishing underlying habits of thought and technique
that are part of the process of mastering any skill or subject.  As
such Mastery is a unspoken subject of the Trivium that is not formally
given a name but is taught indirectly.

This doesn't mean that Mastery is an un-spoken process.  The process
of mastering a subject or skill is well known.  It is not an easy
process, and there are no short-cuts, but it is deeply fulfilling.  In
many respects Mastery is the foundation that civilization is built on.


Mastery comes down to three things:

   - knowledge
   - technique
   - process


Mastery: George Leonard

5 keys to long-term success:

  - Instruction;
  - Practice;
  - Surrender;
  - Intentionality; and,
  - The Edge - Push the envelop.

Mastery is:

  - The process where what was difficult becomes both easier and
    more pleasurable;
  - Long-term dedication to the journey - not the bottom line;
  - Gaining mental discipline to travel further on your journey;
  - Being goalless;
  - Realizing that the pleasure of practice is intensified;
  - Creating deep roots;
  - Knowing that you will never reach a final destination;
  - Being diligent with the process of mastery;
  - Your commitment to hone your skills;
  - After you have reached the top of the mountain, climb
    another one;
  - Being willing to practice, even when you seem to be getting
    no where;
  - Making this a life process;
  - Being patient, while you apply long-term efforts;
  - Appreciating and even enjoying the plateau, as much as you do
    the progress;
  - Practicing for the sake of practice;
  - Winning graciously, and losing with equal grace;
  - Placing practice, discipline, conditioning and character
    development before winning;
  - Being courageous;
  - Being fully in the present moment;
  - Realizing that the ultimate goal is not the medal, or the
    ribbon, but the path to mastery its self (The "I am" stage);
  - Being willing to look foolish;
  - Maintaining flexibility in your strategy, and in your
    actions;
  - A journey; and,
  - Determination

** Practice

 - [[bib:coyle:2012][The Little Book of Talent | ]]Daniel Coyle
 - [[bib:coyle:2009talent][The Talent Code]] | Daniel Coyle
 - [[bib:colvin:2008talent][Talent is Overrated]] | Geoff Colvin
 - [[bib:shibata:2017overlearning][Overlearning hyperstabilizes a skill by rapidly making
   neurochemical processing inhibitory-dominant]] | Kazuhis
   Shibata, etal.
 - [[bib:greene:2012mastery][Mastery]] | Robert Greene
 - [[bib:leonard:1992mastery][Mastery. The Keys To Success And Long Term Fulfillment]] |
   George Leonard
 
** (Deep Work) => Flow

  - [[https://www.robinwieruch.de/lessons-learned-deep-work-flow/][(Deep Work) => Flow]] | RWieruch

#+begin_quote
Shallow Work: “Non-cognitively demanding, logistical-style
tasks, often performed while distracted. These efforts tend
to not create much new value in the world and are easy to
replicate.”

Deep Work: “Professional activities performed in a state of
distraction-free concentration that push you cognitive
capabilities to their limit. These efforts create new value,
improve your skill, and are hard to replicate.”

-- [[https://www.robinwieruch.de/lessons-learned-deep-work-flow/][(Deep Work) => Flow]] | RWieruch
#+end_quote


** Care

Deeply caring is central to everything....

Steven Job's deeply cared about the products that he built,
and lavished as much attention to the parts that people
would never see as what they would.

#+begin_quote
But he also thought that there was a special kind of
technological beauty, uniquely realizable in the medium of
computers, which itself verged on, and sometimes attained,
the status of art. Certainly he aspired to artistic
success. In 1984, he had the signatures of the core
Macintosh engineers engraved on the inside of the machine;
in 1988, introducing the NeXTcube at Davies Symphony Hall,
in San Francisco, he held up one of its circuit boards and
called it “the most beautiful printed circuit board I’ve
ever seen in my life.” (The audience applauded.) He loved
“design,” but yearned for something grander and more
emotional.

-- [[http://www.newyorker.com/culture/cultural-comment/was-steve-jobs-an-artist][Was Steve Jobs an Artist?]]  | The New Yorker
#+end_quote

A stone carver working 25 meters off the ground, carving the
backs of the heads of gargoyles that only the birds and bats
would ever see would be in complete agreement with Jobs.


Find references to Seattle legislature building with hidden
sculptures

* Things You Should Know

  - [[http://programmer.97things.oreilly.com/wiki/index.php/97_Things_Every_Programmer_Should_Know][97 Things Every Programmer Should Know]] | O'Reilly Media
  - [[http://programmer.97things.oreilly.com/wiki/index.php/Other_Edited_Contributions][Other Edited Contributions]] | O'Reilly Media
  - [[http://programmer.97things.oreilly.com/wiki/index.php/Contributions_Appearing_in_the_Book][Contributions Appearing in the Book]] | O'Reilly Media

