#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Rhetoric
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-rhetoric.org
  :Created: 2017-03-10T15:02@Prek Leap (11.642600N-104.919210W)
  :ID: 03cf0f32-e082-4651-a8a5-bda176ae1c8e
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>


#+begin_src emacs-lisp
(let ((git-repo "./"))
  (git-run "log" "v00.01.01...HEAD --pretty=<li>%s</li>"))
#+end_src

#+RESULTS:
#+begin_example
commit c31c1e61d5da4a99fde397cc8c7b6d6c553ad6ed
Author: Deerpig <brad@chenla.la>
Date:   Tue Mar 28 18:06:35 2017 +0700

    moved text to deploy-social

commit 7c7e339819217ce5ab6d7394f5a9df7eeede01c1
Author: Deerpig <brad@chenla.la>
Date:   Mon Mar 27 21:05:01 2017 +0700

    golden rule links

commit 918243b25254b9377f8c69f64392f0a3730dd09a
Author: Deerpig <brad@chenla.la>
Date:   Mon Mar 27 20:43:28 2017 +0700

    added link to TedTalk
#+end_example



* Introduction


** Memory

- [[bib:yates:2016memory][The Art of Memory]] | Yates
- [[bib:smile:2012memory][The Memory Palace - Learn Anything and Everything]] | Smile
- [[bib:davies:2009grimoires][Grimoires: A History of Magic Books]] | Davies


The Art of Memory was part of the medieval Trivium....


#+begin_quote
I purchased The Art of Memory in January 2010, so it was what you
could call a "slow burner." Basically, I bought it, read 20 pages and
then put it on a book shelf for 18 month in order to occasionally look
at it and go, "Nope." However, my attitude was changed when I read
Grimoires: A History of Magic Books, earlier this year. Grimoires
spurred me to think about the relation of magic and occult knowledge
to the transition from the religion centered European Middle Ages to
the Scientific/Mathematical based present.

Understanding the relationship between Magic and Modernity requires a
great deal of context. Specifically, the mind-set or "mentalites" of
people living back then, and how what we think today could possibly be
related to how they thought then.

The fulcrum point of this transition from "Middle Ages" to "Modernity"
was the Renaissance: It was a point where old non Christian/Religious
ideas were rediscovered AND new bodies of knowledge or "disciplines"
(or, if you are really lame "discourses.") were combined with the
existing religious mentalite of the folks living in France, Spain,
Italy and Germany (not England.)

The Art of Memory was an aspect of Rhetoric, and as such had a "place"
in the medieval scheme of 'higher education.' Specifically, Rhetoric
was a part of monastic scholars called the "trivium." (the other
members were grammar and logic.) The Trivium was a medieval equivalent
of our modern "reading, writing and 'rithmatic." Rhetoric, then, was
"the study of the use of language with persuasive effect." (Wiki)

An element of this study was the "Art of Memory." In the ancient,
classic sense, the Art of Memory basically consisted of memorizing a
specific impressive place/location, identifying the distinguishing
points of interest inside the building and attaching the parts of your
speech to those features to cue your memory during the speech you are
no doubt giving.

Basically, what happened in the Renaissance is that people started
building out this "art of memory" and turned it into something much
more complicated and interesting by adding levels of detail and
incorporating different influences "into the mix" as it were. You
could think of it like a modern musical category like rock music with
all it's divergent paths, except here it's "types of art of memory."

Over the course of the 16th and 17th century, the embellished
Renaissance era rhetorical tradition went "psych," it went "straight"
and it went "dark." The Renaissance twist on Rhetoric didn't each
England until well into the 17th century/Elizabethan era, so most of
the Art of Memory takes place on the continent, with the area of
interest shifting from Italy (first), to France and Spain and then to
England and Germany.

The psych tradition of Rhetoric incorporated Kabbalistic letter study,
psuedo-Classical Egyptian Style Occultism and Astrology into the
mix. Readers, who were undoubtedly either Italian noblemen, Artists or
Students or Parisian Students, were treated to convoluted metaphysical
speculation and complex circular charts with wheels inside
wheels. This psych twist was to maintain the ability to inspire right
down into the modern period. In one of The Art of Memory's pay-off
chapters, Yates makes the (convincing) argument that the Masonic
Imagery of buildings and occultism descends from the last remnants of
this psych Rhetoric style, specifically the writings Giordano
Bruno. Bruno was an author who was super obscure and elaborate, and he
operated at the end of the period surveyed in France, England and
Germany. Yates makes the case that it is plausible that he could have
been responsible for inspiring Shakespearean drama in England the
Masonic movement in Germany.

I think he makes a good case in that regard, and I think Modern
Library agrees because it was named "One of Modern Library's 100 Best
Nonfiction Books of the Twentieth Century."

The "straight" tradition of Rhetoric represented the integration first
of the religious philosophy of Thomas Aquinas, including his
neo-platonism. One of the main differences in the beginning of the
split of Rhetoric between "psych" and "straight" is the effort to
maintain and amplify the complexity of the art of memory while
stripping it of it's more visual elements. What starts in the Catholic
church continues through the Reformation. Yates points out that the
move by "straight" Rhetoricians to elaborate their own "Art of Memory"
has an analog in the icon smashing paroxysms of the Reformation. This
branch of Rhetoric influenced early Modern Philosophers and Science,
and was quite crucial in the crystallization of the idea of "Method"
(as used in "THE SCIENTIFIC METHOD") in addition to being the obvious
point of departure for modern Philosophy.

The "dark" tradition of Rhetoric is largely ignored by Yates, but if
you are interested in that wing, check out Davies Grimoires: A History
of Magic Books. I think that it's quite clear that modern ideas of
witchcraft, devil worship, magic spells, witches etc is largely bound
up in this "dark wing" of Rhetoric. The overlap between the "psych"
wing and the "dark" wing is substantial, but obviously the dark stuff
was more controversial, and psych stuff was itself suspect because it
incorporated occult materials via classical or pseudo-classical
sources.

All of these areas seem like fertile fields for inspiration, since
they hover right at the edge of mentality, like a barely remembered
folk tale. The imagery itself is quite elaborate and the source
material is not accessible to the general public.

-- [[https://www.amazon.com/gp/customer-reviews/RIGRYG8L7ZBCM/ref=cm_cr_dp_d_rvw_ttl?ie=UTF8&ASIN=0226950018][Top 100 Non Fiction of Twentieth Century: Merited]] | S.Pactor, Amazon Review
#+end_quote

* Malory Quote


#+begin_quote
But it is doubtful whether the literary genre thus created
would have prospered as it did if it had not inherited at an
early stage another feature of contemporary learning.  If
/grammatica/ can be said to have shown how a given set of
incidents could be explained and expanded, /rhetorica/, the
second part of the Trivium, taught poets and story-tellers
the proper use of imagination.  The discipline which in the
later Middle-Ages was to be largely reduced to a mere
stylistic ornamentation had not at that time lost its
original composing function.  In a number of important works
embodying the doctrine of the rhetoricians from by
Quintilian onwards the term /colores rhetoricae/ refers, as
in Cicero, not so much to formal elaboration as to the
'treatment of the matter' from the speaker's or writer's
point of view.  There is a signiificant agreement in this
respect between Quintilian and the three great medieval
scholars closely connected with the Gallic tradition of
rhetoric: Sidonius Apollinaris, Martianus Capella and John
of Salisbury. Sidonius Apollinaris insists on the use of
'colours' because they 'provide boys' themese with pieces to
weave in' and enable the orator to display his talent
despite the meagerbess of his case.  Martianus Capella in
his allegorical description of the seven arts speaks of
rhetoric as /rerum omnium regina/ who has shown 'the power
to move men whither she pleases, or whence, to bow them to
tears, to incite them to rage, to transform the mien and
feeling.  And John of Salisbury goes so far as to attribute
to rhetoric the function normally assumed by /dialectica/:
he uses the term /probani colores/ in the sense of
'amplification of proof', and like his redecessors looks to
rhetoric for means of persausion.  Rhetoric provided
prospective romance writers with three main types of
exercice.  First they were shown how to paraphrase some
speeches in the /Aeniad/ (/loci Vergliani/); next came the
/dictiones ethicae/, or solilioquies with which persons in
history or mythology could be credited on certain
occasions.  The third and most advanced stage of rhetorical
training was reached in the /controversiae/, or
disquistitions on general subjects, of which  there are many
strikig examples in the letters of Sidonius Apollinaris.
All this was, of course, originally intended for use in
discourses, not in works of fiction, but in the common
confusion between the notion of /narratio/ ('statement of
facts in a discourse') and 'narrative', which can be traced
as far back as Quintilian, helped to transfer to
imagainative literature what was in reality a method of
declamation, and the process was further facilitated by the
fact that, as some passages of Sidonius clearly suggest,
/declamatio/ was itself treated as a literary form alongside
the /epos tragoediarum/, the /comoedia/, and the /satira/.
Nothing seems more natural therefore, thanthat rhetorical
devices should have been used for purposes of orginal
composition.  And so, after having been trained by the
grammarians to react to an articulate manner to works of
Latin antiquety, romance writers were able to aquire from
the rhetoricians the habit of expressing through a /fabula/
or /historia/ a point of view of their own.

This habit more than any other single factor helped to shape
courtly romance.  Whatever the subject of the narrative, its
function as conceived by the twelfth- and thirteenth-century
poets is to serve as an expression of a certain type view of
life which we usually describe as 'courtly' to translate in
terms of actions and characters certain subtle varieties of
ssentiment and highly sophisticated code of behaviour.  A
romance might recall the legendary exploits of King Arthur's
knights, or some imaginary event at the court of Byzantium,
or again some episode placed in contemporary French setting;
what it primarily endevours to do it not to give an
impression of life in the lands and the times to which it
subject-matter ostensibly belongs, but to use this
subject-matter as a means of conveying a coherent system of
ideas. 

pg lxxiv-lxxix

/The Works of Sir Thomas Malory/. Ed. Vinaver, Eugène
(1967). 2nd ed. 3 vol. Oxford: Clarendon Press. [[https://en.wikipedia.org/wiki/Special:BookSources/0198118384][ISBN 0-19-811838-4]].
#+end_quote

:SEE: [[https://en.wikipedia.org/wiki/Le_Morte_d%27Arthur][Le Morte d'Arthur]] | Wikipedia

[[https://en.wikipedia.org/wiki/Gustav_Gr%C3%B6ber][Gustav Gröber]]     | Wikipedia
[[https://en.wikipedia.org/wiki/Eug%C3%A8ne_Vinaver][Eugène Vinaver]]    | Wikipedia
[[https://en.wikipedia.org/wiki/John_of_Salisbury][John of Salisbury]] | Wikipedia

* Rhetoric Links
** What did Rhetoric teach?

Martianus Capella, /Marriage/, bk. V, trans. Stahl, pp. 155-214

Cassiodorus, /Institutions/, bk. II, chap. II, trans. Halporn, pp.
178-88 [Chalk]


Martin Camargo, ﾒRhetoric,ﾓ in /The Seven Liberal Arts/, ed. Wagner, pp.
96-124 [Chalk]

** /Rhetorica christiana/

Augustine of Hippo, /On Christian Doctrine/, bk. IV, trans. J.F. Shaw,
pp. 154-203 [CCEL http://www.ccel.org/a/augustine/doctrine/]

Bede, /De schematibus et tropis/ [ﾒConcerning Figures and Tropesﾓ],
trans. Gussie Hecht Tannenhaus, in /Readings in Medieval Rhetoric/, eds.
Miller et al., pp. 96-122 [Chalk; Reg]

 
** /Ars poetica/

Matthew of Vend冦e, /Ars versificatoria/ [/The Art of Versification/],
trans. Aubrey E. Galyon (Ames: Iowa State University Press, 1980), pp.
25-112 [Chalk]

Geoffrey of Vinsauf, /Poetria nova/, trans. Margaret F. Nims (Toronto:
Pontifical Institute of Mediaeval Studies, 1967), pp. 15-93 [Chalk]

** /Ars dictaminis/

John of Garland, /Parisiana poetria/, ed. and trans. Traugott Lawler
(New Haven: Yale University Press, 1974), chaps. 1-4, 7, pp. 3-83,
143-59 (odd numbered pages) [Chalk]

Anonymous of Bologna, /Rationes dictandi/ [/The Principles of
Letter-Writing/], trans. James J. Murphy, in /Three Medieval Rhetorical
Arts/, ed. James J. Murphy (Berkeley and Los Angeles: University of
California Press, 1971), pp. 3-25 [Chalk; Reg]


** /Ars praedicandi/

Thomas of Chobham, /Summa de arte praedicandi/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 614-38 [Chalk; Reg]

Robert of Basevorn, /Forma praedicandi/ [/The Form of Preaching/],
trans. Leopold Krul, O.S.B., in /Three Medieval Rhetorical Arts/, ed.
Murphy, pp. 111-215 [Chalk; Reg]


 

