#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to the Trivium
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-introduction.org
  :Created: 2017-02-13T12:32@Prek Leap (11.642600N-104.919210W)
  :ID: 3485b3fc-3c51-4459-847c-462b7a5d040f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

Keep in mind that this not the Medieval Trivium, though much
has been borrowed from it, including a lot of
nomenclature. It would be better to call this the /Scopic
Trivium/.  We will learn more about Scopic Philosophy later
in this introduction.

The Medieval Trivium was the equivilent of a modern College
or University Bachelor's Degree.  And the Medievel Trivium
is still the ancient ancestor of the Liberal Arts Bachelor's
degree program, though one must often squint with just the
right amount of grimmace to see it at times.


---

There is no small amount of tension in the Trivium between
Grammar, Dialectice and Rhetoric.  Each is a very different
way of understanding the world, relating to it,
communicating with each other about it, and figuring out
what it means.

#+begin_quote
The three arts of the trivium challenge because they are,
fundamentally, different ways of seeing the world. Just as I
saw Stanislavski, Artaud, and Brecht as seeing truth in
fundamentally different ways, so do the three arts. It would
be far easier to be a grammarian, a dialectician, or a
rhetorician rather than being an advocate for the trivium,
because such an advocacy requires embracing contradictions
and living with uncertainty, even paradox.

Although some teachers want politics out of education, we
need to note that education is essentially a political act,
as is parenting. Do we want our children to be just like us,
or do we want them to be different and thus end up
challenging us? This uneasy relationship between control and
freedom is played out in every nation, every classroom, and
every home. This tension is implicit in the relationship
between grammar, dialectic, and rhetoric.

-- Trivium 21 Century
#+end_quote

In a way it's amazing that it held together at all, for so
long, with all three splitting in a very messy divorce will
all parties claiming that they keep the children...

But again, (as I note later) that a lot of this tension is
when there is a major shift in how we do things.

In the time of Plato, that was the shift from the oral to
the written tradition -- in the medieval europe it was
moveable type and Gutenberg Press -- in the 19th and 20th
centuries it was mass media and universal literacy and now
in the 20th century it is the troika of digitization of
text, video and audio; providing anyone of even modest means
with the ability to create and publish information at levels
that was reserved only for media tycoons and heads of state
less than 50 years before, and now, the the unimaginable
centralization of communication channels that determine how
these tools are used, and used against us.

I have a bit of a beef with Platonic forms in any case.
In process philosophy, everything is in the process of
becoming something else.  So when does the platonic form for
a bird come from?  When did dinosaurs stop being dinosaurs
and became birds?  Can something embody multiple ideal forms?
It would seem that this drags in the need for an observer as
well.  Plato would argue that no observer is necessary
because each bird is a shadow of the perfect bird form.  And
how do these forms come into existence?  If forms are
eternal, that implies that the bird form existed from the
big bang for billions of years up until the bird evolved
from the dinosaur.  Does that mean that the forms for all
future creatures and categories exist as well?  Or is the
world of forms a kind of ideal Everett Universe that
contains all possible forms that result from causal-chains?
And what of the imagination.  There is certainly no such
thing as a hobbit, dragon or a unicorn, but for there must
be a platonic form for each of them, in order for people to
be able to understand what a hobbit is.  Then there are
misconceptions, beliefs and dieties.  If monotheists believe
there is a single all powerful god, then is there too a
platonic form for that god, and did that form preceed god's
existence, or determine what form god would take?  Once you
even peek down these rabbit holes forms become far more
cumbersome as a concept than they are worth.  Like the
existence of the  æther, which was thought to be a universal
medium through which allowed light and gravity to travel in
a vacuum, the plato's world of forms is simply not needed.

Does this mean I am advocating an Aristotelian view?

#+begin_quote
The grammarian will tell it like it is, either by agreed
practice or imposed rules; the Socratic dialectician will
ask about it until it is no longer; the Platonic
dialectician will discuss it until ‘ultimate truth’ is
revealed; and the Aristotelian dialectician will use an
approach that should uncover possible truths with differing
degrees of probability.

-- Trivium 21 Century
#+end_quote

This, of course is a gross simplification -- but if these
are the options available, Aristotle provides a better match
to inductive empirical reality.

I can't shake the feeling through, that Aristotle was no
less comfortable with uncertainty than Plato -- Logic is an
enormously powerful tool -- but I wonder how satisfied
Aristotle was with it?  Embracing uncertainty, while still
demanding that we take all possible measures to minimize
uncertainty is on face contradictory, to have a goal which
you must work tirelessly to work towards, but still feel
comfortable knowing that the goal is impossible to achieve.
That truth is a horizon relative to the observer, and that
one can never reach it, only extend that horizon seemingly
forever.  Worse still, is that the horizon receeds before us
and behind us, in space and time.  No matter how large a
number is, you can always add another number to it.
Infinity rightly scares the crap out of most people who
think about it too long.  Which is why anyone who finds the
the concept of an eternal soul comforting, both as reward or
punishment has not really thought about it very hard.  An
eternal heaven is nearly as terrifying as an eternal hell.
Even the Universe is not eternal -- because it had a
beginning, though the end escapes us at the moment.  But
infinity dwarfs even this, because anything with a beginning
can be added to.  The second before the big bang... there is
simply no end to it.  But more likely, we simply have not
yet extended our minds and miserable senses enough to see,
not astute enough to percieve, not wise enough to
understand...



* Scopic Philosophy

It was really only recently that I realized that my relentlessly
evolving concept of Scope had become— while I was not watching—a
philosophy in its own right.

Every Civilization is built on philosophical tradtions that contain
many variations over time and location, but like in Jazz
improvisation, still manage to stay within the theme set at the
beginning.  The Western Tradition that Western Civilization is based
on Greek/Roman tradition.  If there is an Eastern Tradition, it could
be argued that it is based originally on Hindu mytholody and was later
refined into Buddhist/Confucian Tradation.   

It is my belief that a new Tradition will need to be established in
order for a truly distributed, /solar civlization/ to be possible that
reflects the fundemental change that mankind is undergoing that is
redefining its relationship to nature and the universe.

This is not to say that Scopic Philosophy will be the foundation for
/anything/, let along the foundation an underpinning Tradition for a
civilizaion, but I do hope that it will be useful for those who do.

** Components

Scopic Philosophy is modular in that it provides a framework for
understanding how the world works.  But it can also be combined with
any number of classical philosophies of life.  It works extremely well
in combination with Skepticism and Epicureanism.

  - Reconciles Atomist and Holistic views of the World.
  - A concept of Time and Causality based on Process Philosophy
  - A Temporal Model based Scope (Context: LOD, POV ROC)
  - A Dynamicly Changing Cosmology that reflects the current scientic consensus
    of how the Universe works based on the scientific method.
  - Plug-in Philosophy of Life
  - Plug-in Phlosophy of lifelong learning.

* Learning -- onion

think of learning as something akin to the human brain which
is made up in successive layers -- with the reptilian brain
at the core, and eventually adding the limbic system and
finally the neocortex

It's important that knowledge is taught as if it is an onion
that is builds layer apon layer until reaching the present
state of knowledge at the outside which can then be the
basis for building new layers.

Knowing how we have come to know something is important
because it includes all of the blind alleys and walls that
we kept running up against before finally surmounting them
to build up the next layer of the onion.  The history of
knowledge is all about how to build better mousetraps by
first knowing all of the past mousetraps that have been
devised in the past, and how they have worked or not....

* Learning -- disciplines


The mechanical arts were outside of the quadrivium, a rift
that is still with us today

the thing is, we need to stop thinking in terms of
disciplines and rather think in terms of holons and how
cultures (disciplines) look from inside the discipline and
from without.

we also need to start thinking of everything being an
extension of our senses, muscles and neocortex -- there is
nothing that is done for its own sake, at least not if it's
any good or of any use -- beauty is important, in fact it is
critical to our survival -- the decorative arts are also
critical, because they center us where we are and put us in
context with the world around us -- they are an anchor --
when done right (which is rare today)

* Scopic Trivium

can't separate trivium from Latin -- this is important,
because we will be teaching english as a foriegn lanaguage,
even to native speakers -- it will be a very specific
language designed to bridge generations and linguistic drift
so that texts will remain in use over very long time frames.

This will be especially important for scientific papers and
cannonical works -- and translation of older english works
into scopic english will have to be undertaken -- or at the
least that editions are presented that provide glossa and
scholia that define anything that falls outside of Scopic
vocabulary and usage.

This will especially be important for technical terms --
which go in and out of vogue far more often than might be
thought....

The Scopic Trivium this will include:

   - english (a defined subset that will change slower than the
     vernacular)
   - scopic a DSL (domain-specific-language)
   - incantation script (based on CJK)


* Trivium
 

Need to think about the trivium in context with Havelock's
idea of pre-literate modes of thought.  The heavy emphasis
in the trivium on rhetoric as a tool for oratory is solidly
grounded in, the spoken word -- something that we shifted
away from in the modern era -- mass education, and universal
literacy shifted the role of oratory dramatically sometime
towards the end of the 70's -- the tipping point happened
and no one seemed to notice.

We are living in a post-oral world -- which oddly coincides
with a post-literate segmentation of society which places
less importance on the written word, and instead gravitates
towards produced multi-media that seems to attempt to
bi-pass rationality and logic all together and appeal
directly to the emotions that are adrift in a contextless
cloud that swings often violently between desires and fears.
Not only is there no context -- there is no stability,
shifting sands beneath out feet.  This condition is well
known to those in power, in government, religion, and
industry and are used against us, as a tool of control,
which runs diametrically opposite to the role that human
institutions are supposed to provide.  The culture, layer
has been turned against us -- subverting institutions to
make us more afraid, to make descision that are not in our
self interest, and only serve to enrich an elite who are
trapped in their own bubble of desire, fear and hunger for
power and status.  This is why people no longer trust
institutions to provide truth, or justice, or even a living
wage.




** Intro
the tools needed to study the quadrivium

  - Grammar  :: symbol systems to communicate and manipulate langauge
    - written language -- tools to express written language - chalk,
      ink and bits.  
    - reading :: 4 kinds
    - etymology :: history & conext of words
    - history :: time as narratives 
      - process philosophy
      - oral, written & code traditions
    - number :: 
    - code :: dynamic manipulation of text (everything is text)
    - maps :: spatial symbol systems
    - bitmaps :: images / video
    - geometry / vectors :: 
    - audio ::    
  - Logic    ::
    - analytical and synoptic reading
  - Rhetoric :: communication
    - composition
    - communication
    
The Trivium should be started at the age of 11, no earlier.  At this
age the child is able to begin to comprehend complex and abstract
concepts.

The Trivium provides the child with the intellectual tools to express
thoughts in spoken, written and code form, communicate with others,
and to think rationally and critically.

These arts will be a foundation that the child will be able use the
rest of their lives and form the basis for self-directed and directed
study in the future.

**** Subjects included

- history
- literature
- 

** Grammar

#+begin_quote
Religions and leaders, however, soon saw the potential of
writing and used it to help establish their own mythology
and rules. It was clear that the written word had power; due
to its permanence it had become a symbol of authority. This
meant that rules could become fixed; something is more
difficult to challenge when it is written down. The
accountants, bureaucrats, pedantic rule makers,
authoritarians, and religious zealots were all early
adopters of written language; the poets, dramatists,
philosophers, novelists, and journalists were laggards. This
monstrous conclusion perhaps could explain the problems that
many have with the study of grammar. It is not that it isn’t
needed and doesn’t exist in our utterances, but that the way
it is taught – its rules and perceived lack of flexibility –
is authoritarian.

-- Trivium 21 Century
#+end_quote


But learning by rote -- rules, drills, and endless lists of
vocabulary is boring but it lies at the heary of practice
and mastery -- of rewiring your brain.  It takes time, it's
not pleasant -- it's hard work damn it!  

Grammar became the foundation of the Trivium because it
provided the scaffolding that makes everything else
possible.  Communication, art, beauty, drama, commerce,
betrayal, and profundity all require that all parties who
talk to each other share common knowledge between them that
makes utterances comprehensible -- we all have to be on the
same page, speaking the same language -- literally and
figuratively to exchange information -- it not, it's just
unintelligible noise.  This is what grammar provides us.

But it's important to understand that the rules of language
is only the tip of the iceberg here.  As Tolkien said, you
can't have language without an underlying mythology.
Societies are built on rules of behavior, stories, and ways
of structring things in a way that everyone in the group can
understand. 

The other role of grammar is continuity -- after all writing
is a tool for time travel -- it is grammar that ensures that
things get remembered in standardized ways that can be
passed on to future generations -- not just the next
generation, but to leapfrog generations to talk directly to
distant future descendents who only know of you from the
words that have been written and preserved through the
centuries or millennia.


** Dialectic

#+begin_quote
Man, being the servant and interpreter of Nature, can do and
understand so much and so much only as he has observed in
fact or in thought about the order of Nature: beyond this he
neither knows anything nor can do anything [p. 47].

-- Francis Bacon
#+end_quote

Dialectic in the Trivium has later been characterized as
logic, especially aristotelian logic.  But it is better
thought of as a dialectic -- an exchange of questions and
answers that is meant to come to some kind of truth.

In fact dialectic has been called not just logic, but logos
as well.  Logos is a slippery word which has changed in
meaning over time.  Christians define it as sort of
"universal truths" from God but it also simply means /word/.

It is the dialectic that questions the authority of grammar,
it keeps grammar honest, and keeps moving the goalpost, by
always taking facts and putting them into new contexts, that
may or may not result in new facts, or discovery of
falsehoods.  The dialectic keeps grammar from fossilizing...

To modern ears, logic seems to make a lot more sense -- but
isn't the inductive empirical scientific method just that?
Putting questions to things, making observations (which
answer back) that results in new understandings of the
world?

It's too easy to label the dialectic as simply the Socratic
Method, that's is only a small part of it.  Sure, you're
subjected to it in Harvard Law School -- though the
teachers, if the film, The Paper Chase is any indication,
are really hardcore grammerian's in dialectical clothing....

but if this is at the heart of the scientific method and
pretty much the foundation of our civilization, then it is
pretty damn important.

The thing is, the dialectic is messy, it embraces
uncertainty, complexity and contradiction -- it's not neat
and orderly and tied up with a bow like grammar.  And it's
not dolled up on the podium spouting or bellowing or doing
whatever it takes to convince -- rhetoric and grammar has an
agenda which is based on certainty.  Dialectic just smiles
and reminds us that we're talking out our asses.

So dialectic is a process that embraces uncertainty and
leads to truth.  But is that truth or TRUTH?  How can
questions lead us to what is true -- or put in another way,
help us to know what is real or not?

Are there higher truths -- Logos?  Is truth hierarchical,
with some truths truthier than others?  Plato certainly
thought so -- in fact he concocted the whole world of forms
and tacked it onto dialectic to make it work.

But truth doesn't exist in nature -- it's a label humans use
to understand the world.  There is just the world and the
world just is.  It's our brains which are constantly taking
in raw sensory data and trying to make sense of it -- by
establishing limits on things -- a chair is a chair because
of all the things it is not.  A chair is not a spoon or a
duck or a cheese burger.  We are constantly trying to find
the sculpture inside the block of marble.  The world is a
block of marble -- it's only us who try to make distinctions
of which part of the block are what.  So in that sense, no,
there is no higher or greater truth -- because if you take
away the brain trying to impose order on the world, the
world keeps going on happily without us, because there is
nothing trying to do this except us -- a side effect of
certain types of Life.

This is not to say that truth is not important -- without it
we die.  Figuring out what is true and false, fact and
fiction, real or illusion determines if we survive or not.
So yes, dialectic is vitally, critically important.  And
every time someone willfully lies -- it puts us all in very
real mortal danger.

---

cultural relativists, along with deconstructionist nihilism
have made a fucking mess of things.  not everything is
relative -- not everything is interpretation -- when you
have been burned by a lit match, your opinion on the burn will
not change the back that a chemical reaction released enough
concentrated heat to cook your flesh

but what are those limits?  in a nutshell, possible causal
chains of events, and which side of a holon one is observing
something from -- is it inside looking out, or outside
looking in.


** Rhetoric
