#   -*- mode: org; fill-column: 60 -*-
#+TITLE: What We Don't Know
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-unknown.org
  :Created: 2017-04-12T17:14@Prek Leap (11.642600N-104.919210W)
  :ID: 9a1fd56d-413f-4f8b-a897-39fff03aea1d
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

#+begin_quote
"It ain't what you don't know that gets you into trouble. It's what
you know for sure that just ain't so." 

-- Mark Twain
#+end_quote

* Introduction

This keeps cropping up so much, in so many different places that it
deserves its own file.

We as individuals and we as a modern civilization take credit for
knowing far more than we do.  In fact, what we do know, is the tinest
of crumbs compared to the barn-sized loaf of what we don't.  And even
that crumb, if not constantly maintained would eventually dry out and
turn to dust.

Scientists understand this more than most, that we are just scratching
the surface of discoverying /everything/.

But the other side of the unknown is the degree to which we know or
don't know anything in the first place.  Learning to embrace and
accept uncertainty is one of the greatest challenges that we face.
Because what science is discovering is that uncertainty is the norm,
rather than the exception in nature.  We are learning that most if not
all things have dual natures that can be known in different ways
depending on the context in which it is observed.  This is not an
argument for realativism, or that subjective belief trumps empirical
observation and rational inquiry.  Indeed, it is quite opposite, the
world is knowable in many respects, so long as it is understood that
it can not be predicted.

Different approaches to understanding the world, yield different world
models that may contradict other world models.  The interesting thing
is that such contradictions and even paradoxes illustrate the dual
nature of many aspects of nature and reality.  There are many times
that contraditions arise that will provide to be consistent across all
world views that are based on empirical observation.   This is how
knowledge moves forward.

But it is important that we embrace multiple world models, because the
sum of all of these truths are greater than their parts and that is
the only way to come to terms with contradictions, paradoxes and dual
natures that are consistent across all world models.

When a person or group declares one world model to be true and that
all others are false, it becomes a fossil, an ossified snapshot of a
living world model that is now an ideology, whose dogma is frozen and
will increasingly be out of sync with the world it is describing.
It's like using a map of London drawn in the 1600's to navigate the
city in 2017.  Some things will still be there, but not a lot, and
most things will not be on the map at all.  This is what the
ideologues and the so-called /fundementalist/ belief systems are
pushing; an old map that doesn't even show where the tube stations
are.

* 積ん読 (Tsundoku)

 - [[https://en.wikipedia.org/wiki/Tsundoku][Tsundoku]] - Wikipedia
 - 


/Tsundoku/ (積ん読) is a japanese word for the act or process or
aquiring books and other reading material and letting them pile up
unread.[fn:1]


#+begin_quote
Derrida: (shows his library) "I haven't read all the books that are
here"

Interviewer: "But you've read most of them? 

Derrida: "No, no... three or four... but I've read those four really,
really well."

-- [[https://youtu.be/tdumO88JMxw][Derrida documentary]]
#+end_quote


#+begin_quote
Even when reading is impossible, the presence of books acquired
produces such an ecstasy that the buying of more books than one can
read is nothing less than the soul reaching towards infinity… we
cherish books even if unread, their mere presence exudes comfort,
their ready access, reassurance.

-- [[https://en.wikipedia.org/wiki/A._Edward_Newton][A. Edward Newton]]
#+end_quote

#+begin_quote
The writer Umberto Eco belongs to that small class of scholars who are
encyclopedic, insightful, and nondull. He is the owner of a large
personal library (containing thirty thousand books), and separates
visitors into two categories: those who react with “Wow! /Signore
professore dottore Eco/, what a library you have! How many of these
books have you read?” and the others — a very small minority — who get
the point that a private library is not an ego-boosting appendage but
a research tool. Read books are far less valuable than unread
ones. The library should contain as much of what you do not know as
your financial means, mortgage rates, and the currently tight
real-estate market allows you to put there. You will accumulate more
knowledge and more books as you grow older, and the growing number of
unread books on the shelves will look at you menacingly. Indeed, the
more you know, the larger the rows of unread books. Let us call this
collection of unread books an antilibrary.[fn:2]

-- Nassim Nicholas Taleb | The Black Swan
#+end_quote

This is similar to the experience that many people feel (or now
largely felt) when browsing the stacks in a good research library.
The LOC Catalog system, for all it's shortcomings, is good at shelving
books on each topic together.  I used to keep an index card that had
the prefixes for all of the different sections that I visited most
often.  And this cheat sheet worked in any library using the LOC
Catalog system.  No matter how many times I visited each section, I
would come back again and again, though I knew that the chances of new
material to be very slim.  That wasn't the point.  As I read and
researched, I came to know all of the books in each section and their
relationship to each other.  Though I could never have read even a
fraction of them, it helped me to form a mental map of work in
different fields.  This is not something that can be done at present
in electronic collections.  Links on a web page, or search results
don't capture that same mapping LOC catalog's mapping that was
physically manifest on wood and metal shelving.  This is a useful tool
that will eventually be reinvented for the electronic networked age.
But likely it will only happen when electronic libraries can be
assembled in ways similar to physical lending and research libraries.
The tyranny of the publishing industry has fought tooth and nail to
destroy the library, to maximize profits.  All of the paywalls and
walled gardens place the experience of browsing the stacks out of
reach and will stay that way for some time to come.


#+begin_quote
We tend to treat our knowledge as personal property to be protected
and defended. It is an ornament that allows us to rise in the pecking
order. So this tendency to offend Eco’s library sensibility by
focusing on the known is a human bias that extends to our mental
operations. People don’t walk around with anti-résumés telling you
what they have not studied or experienced (it’s the job of their
competitors to do that), but it would be nice if they did. Just as we
need to stand library logic on its head, we will work on standing
knowledge itself on its head.

-- Nassim Nicholas Taleb | [[bib:taleb:2007black][The Black Swan]]
#+end_quote

* Further Research Materials

 - [[bib:taleb:2007black][The Black Swan]] | Nicholas Taleb

 - [[https://www.brainpickings.org/2015/02/02/the-island-of-knowledge-marcelo-gleiser/][How to live with mystery in a culture obsessed with
   certitude]] | Brain Pickings
 - [[https://www.brainpickings.org/2014/09/16/hannah-arendt-the-life-of-the-mind/][How unanswerable questions give shape to the human experience]] | Brain Pickings
 - [[https://www.brainpickings.org/2014/12/08/the-world-split-open-marilynne-robinson-beauty-writing/][Hhe beauty of the unknown]] | Brain Pickings

 - [[bib:sagan:2007varieties][The Varieties of Scientific Experience]] | Carl Sagan
 - [[bib:gleiser:2014island][The Island of Knowledge]] | Marcelo Gleiser
 - [[https://en.wikipedia.org/wiki/Hannah_Arendt][Hannah Arendt]] | Wikipedia
 - [[bib:arendt:1998human][The Human Condition]]  | Hannah Arendt
 - [[bib:arendt:1981life][The Life of the Mind]] | Hannah Arendt

* Footnotes

[fn:2] For more background on the quote see: [[http://languagehat.com/a-quote-on-bibliomania/][ A Quote On Bibliomania]] |
languagehat.com

[fn:1] I wish this was relevant, but it /is/ amusing:

#+begin_quote 
tjr: "If you call your collection of unread books your
     /anti-library/, what do you call your collection of books still
     enclosed within postal delivery boxes that you haven't even opened
     yet?

cirgue: "Schrodinger's library"

-- [[https://news.ycombinator.com/item?id=14087536][Umberto Eco's Anti-Library]] (2015) | Hacker News Discussion Thread
#+end_quote
