#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Logic
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-logic.org
  :Created: 2017-03-11T21:31@Prek Leap (11.642600N-104.919210W)
  :ID: ff5e852a-bcbb-48e2-a4b2-dbf678f24fbe
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

#+begin_quote
To appreciate the form and content of these debates, it is
convenient to start with the so-called /trivium/, the triad
of topics -- grammar, dialectic and rhetoric -- that served
at the lower tier of the Seven Liberal Arts.  These
categories, personified  as the deven daughters of
philosophy, comprised 'the rational endeavours of man'
(Katzenellenbogen, 1966, pp.47 &.39). To become rational
beings, learners should acquire such knowledge.  In
discussions of the trivium, dialectic is sometimes given an
alternative label -- logic; as indicated in the remainder of
this paper, medieval logic was not the same as the humanist
dialectic.

*Knowledge and Communication*

The Liberal Arts comprised yesterdays learning that was to
be learned by tomorrow's male adults.  The Liberal Arts were
self-referential.  They were both structured bodies of
knowledge and structured instruments for the communication
of knowledge.  To learn /from/ previous knowledge was also
to learn /through/ previous knowledge.  At the same time,
however, the structure of the Liberal Arts was ill-defined.
They were fluid rather than fixed bodies of knowledge and,
as a result their form as communication media was equally
imprecise.  They were more texts than textbooks.

The same argument applies to the trivium.  It is more easily
understood as an amorphous stage of learning than as a
henady set of tools for learning.  Collectively, grammar,
dialectic and rhetoric related to knowledge about -- and for
-- human communication.  Grammar was the chassis of
communcation, and dialectic and rhetoric comprised knowledge
about how the bodywork of communication should be moulded
and finished.  If knowledge and grammar fostered the ability
to write or speak Latin, dialectic and rhetoric underpinned
the capacity to produce Latin employed in the higher arts
(notably theology).  Further, the history of the trivium is
a history of how such 'good' Latin was characterised as a
body of knowledge to be learned, from and through.




-- [[bib:hamilton:2003instruction][Instruction in the Making]] | Hamilton
#+end_quote



* Dialectic Links

** What did Dialectic teach?

Martianus Capella, /Marriage/, bk. IV, trans. Stahl, pp. 106-154

Cassiodorus, /Institutions/, bk. II, chap. III, trans. Halporn, pp.
188-208 [Chalk]

 
Eleanore Stump, ﾒDialectic,ﾓ in /The Seven Liberal Arts/, ed. Wagner,
pp. 125-46 [Chalk; Reg]

 

** The Problem with Education These Days

John of Salisbury, /Metalogicon/, Prologue; bk. I, chaps. 1-12; bk. II,
chaps. 1-20; trans. McGarry, pp. 3-37, 73-141

 

** The Point of It All

John of Salisbury, /Metalogicon/, bks. III-IV, trans. McGarry, pp. 142-276

 

** Applied Dialectic: Universals and Particulars

Aristotle, Porphyry, Boethius, Garlandus Compotista, and Abelard, in
/Basic Issues in Medieval Philosophy/, eds. Bosley and Tweedale, Topic
VI, pp. 352-92 [Chalk]

John of Salisbury, /Metalogicon/, bk. II, chaps. 17-20; bk. III, chaps.
1-4; trans. McGarry, pp. 111-41, 146-70
