#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Mastery
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-mastery.org
  :Created: 2017-02-13T12:13@Prek Leap (11.642600N-104.919210W)
  :ID: 85b5b600-1212-475e-8aed-2ff90df670dc
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


#+begin_quote
    Vita brevis,
    ars longa,
    occasio praeceps,
    experimentum periculosum,
    iudicium difficile.

    Life is short,
    and art long,
    opportunity fleeting,
    experimentations perilous,
    and judgment difficult. 

--  Hippocrates 


"The lyf so short, the craft so long to lerne" -- Chaucer

    [[https://en.wikipedia.org/wiki/Ars_longa%2C_vita_brevis][Ars longa, vita brevis]] - Wikipedia
#+end_quote

* Introduction

I'm now going to break up mastery into four parts:

  - Mastery  :: Deals with the larger concepts of mastering a
                discipline and a basic philosophy of life
                work, learning and balance.
  - Practice :: The deliberate regular practice of anything
                that is one of the two pillars of work and
                learning.
  - Otium    :: The flip side of Practice which is
                deliberate, rest and contemplation.
  - Negotium :: Dealing with a person's public roles and
                interactions with people, family, collective
                projects, business, management roles etc.

---

Mastery is the process of lifelong learning.  The Trivium can be thought of
as a means of establishing underlying habits of thought and technique
that are part of the process of mastering any skill or subject.  As
such Mastery is a unspoken subject of the Trivium that is not formally
given a name but is taught indirectly.

This doesn't mean that Mastery is an un-spoken process.  The process
of mastering a subject or skill is well known.  It is not an easy
process, and there are no short-cuts, but it is deeply fulfilling.  In
many respects Mastery is the foundation that civilization is built on.


Mastery comes down to three things:

   - knowledge
   - technique
   - process


Mastery: George Leonard

5 keys to long-term success:

  - Instruction;
  - Practice;
  - Surrender;
  - Intentionality; and,
  - The Edge - Push the envelop.

Mastery is:

  - The process where what was difficult becomes both easier and
    more pleasurable;
  - Long-term dedication to the journey - not the bottom line;
  - Gaining mental discipline to travel further on your journey;
  - Being goalless;
  - Realizing that the pleasure of practice is intensified;
  - Creating deep roots;
  - Knowing that you will never reach a final destination;
  - Being diligent with the process of mastery;
  - Your commitment to hone your skills;
  - After you have reached the top of the mountain, climb
    another one;
  - Being willing to practice, even when you seem to be getting
    no where;
  - Making this a life process;
  - Being patient, while you apply long-term efforts;
  - Appreciating and even enjoying the plateau, as much as you do
    the progress;
  - Practicing for the sake of practice;
  - Winning graciously, and losing with equal grace;
  - Placing practice, discipline, conditioning and character
    development before winning;
  - Being courageous;
  - Being fully in the present moment;
  - Realizing that the ultimate goal is not the medal, or the
    ribbon, but the path to mastery its self (The "I am" stage);
  - Being willing to look foolish;
  - Maintaining flexibility in your strategy, and in your
    actions;
  - A journey; and,
  - Determination

** Practice

 - [[bib:coyle:2012][The Little Book of Talent | ]]Daniel Coyle
 - [[bib:coyle:2009talent][The Talent Code]] | Daniel Coyle
 - [[bib:colvin:2008talent][Talent is Overrated]] | Geoff Colvin
 - [[bib:shibata:2017overlearning][Overlearning hyperstabilizes a skill by rapidly making
   neurochemical processing inhibitory-dominant]] | Kazuhis
   Shibata, etal.
 - [[bib:greene:2012mastery][Mastery]] | Robert Greene
 - [[bib:leonard:1992mastery][Mastery. The Keys To Success And Long Term Fulfillment]] |
   George Leonard
 
** (Deep Work) => Flow

  - [[https://www.robinwieruch.de/lessons-learned-deep-work-flow/][(Deep Work) => Flow]] | RWieruch

#+begin_quote
Shallow Work: “Non-cognitively demanding, logistical-style
tasks, often performed while distracted. These efforts tend
to not create much new value in the world and are easy to
replicate.”

Deep Work: “Professional activities performed in a state of
distraction-free concentration that push you cognitive
capabilities to their limit. These efforts create new value,
improve your skill, and are hard to replicate.”

-- [[https://www.robinwieruch.de/lessons-learned-deep-work-flow/][(Deep Work) => Flow]] | RWieruch
#+end_quote

This quote is another way of saying /Ratio/ and /Intellectus/ 

#+begin_quote
The medievals distinguished between the intellect as
/ratio/and the intellect as /intellectus/. /Ratio/ is the
power of discursive thought, of searching and re-searching,
abstracting, refining, and concluding [cf.  Latin
/dis-currere/ ”to run to and fro”], whereas /intellectus/
refers to the ability of ”simply looking” (/simplex
intuitus/), to which the truth presents itself as a
landscape presents itself to the eye. The spiritual knowing
power of the human mind, as the ancients understood it, is
really two things in one: /ratio/ and /intellectus/, all
knowing involves both. The path of discursive reasoning is
accompanied and penetrated by the /intellectus’/ untiring
vision, which is not active but passive, or better,
receptive - a receptively operating power of the intellect.

-- Pieper Leisure The Basis of Culture
#+end_quote


Intellectus is not the same as shallow -- it is grasping
something in total.  Though shallow can be thought of as
intellectus, but with a negative connotation.

Another way of seeing this is as a holon, /intellectus/ sees
something as a whole, where as /ratio/ (see quote from
Pieper's /Leisure As a Basis of Culture/) as a sees and dives into
all of the parts that make up that whole.  Shallow is seeing
the whole in the ground, ratio is diving down the rabbit hole.



** Care

Deeply caring is central to everything....

Steven Job's deeply cared about the products that he built,
and lavished as much attention to the parts that people
would never see as what they would.

#+begin_quote
But he also thought that there was a special kind of
technological beauty, uniquely realizable in the medium of
computers, which itself verged on, and sometimes attained,
the status of art. Certainly he aspired to artistic
success. In 1984, he had the signatures of the core
Macintosh engineers engraved on the inside of the machine;
in 1988, introducing the NeXTcube at Davies Symphony Hall,
in San Francisco, he held up one of its circuit boards and
called it “the most beautiful printed circuit board I’ve
ever seen in my life.” (The audience applauded.) He loved
“design,” but yearned for something grander and more
emotional.

-- [[http://www.newyorker.com/culture/cultural-comment/was-steve-jobs-an-artist][Was Steve Jobs an Artist?]]  | The New Yorker
#+end_quote

A stone carver working 25 meters off the ground, carving the
backs of the heads of gargoyles that only the birds and bats
would ever see would be in complete agreement with Jobs.


Find references to Seattle legislature building with hidden
sculptures

* Things You Should Know

  - [[http://programmer.97things.oreilly.com/wiki/index.php/97_Things_Every_Programmer_Should_Know][97 Things Every Programmer Should Know]] | O'Reilly Media
  - [[http://programmer.97things.oreilly.com/wiki/index.php/Other_Edited_Contributions][Other Edited Contributions]] | O'Reilly Media
  - [[http://programmer.97things.oreilly.com/wiki/index.php/Contributions_Appearing_in_the_Book][Contributions Appearing in the Book]] | O'Reilly Media

* Mastery Learning 

 - [[https://en.wikipedia.org/wiki/Mastery_learning][Mastery learning]] | Wikipedia

#+begin_quote
Mastery Learning has been one of the most highly
investigated teaching methods over the past 50 years. While
it has been the subject of high criticism, it has also been
found to have resounding success when implemented
correctly. A meta-analysis by Guskey & Pigott (1988)
looked at 46 studies that implemented group-based mastery
learning classrooms. Results found consistently positive
effects for a number of variables including "student
achievement, retention of learned material, involvement in
learning activities, and student affect". However, a
notable variation was found within student achievement and
it was believed this was due mainly to the subject being
taught. Courses such as science, probability, and social
studies yielded the most consistent positive results, while
other subjects were varied.

Another large-scale meta analysis conducted by Kulik et
al. (1990) investigated 108 studies of mastery programs
being implemented at the elementary, secondary, and
post-secondary level. Results revealed positive effects in
favour of these teaching strategies, with students also
reporting positive attitudes toward this style of
learning. This study also found mastery programs to be most
effective for weaker students.

Despite the empirical evidence, many mastery programs in
schools have been replaced by more traditional forms of
instruction due to the level of commitment required by the
teacher and the difficulty in managing the classroom when
each student is following an individual course of
learning. However, the central tenets of mastery
learning are still found in today's teaching strategies such
as differentiated instruction and understanding by
design.

-- [[https://en.wikipedia.org/wiki/Mastery_learning][Mastery learning]] | Wikipedia
#+end_quote


It's not surprising that mastery learning is often abandoned
in traditional educational programs.  The technique is at
odds with to many assumptions made in modern education.

Industrial age education is based on the factory assembly
line.  Factories treat all products to be identical copies
of each other.  If they aren't identical they are rejected
and discarded.  The system assumes that all students in a
class advance together.  The system is designed from the
bottom up to do this.  It is not only difficult to introduce
a system where students advance at different rates, it is a
threat to the system itself.


* Self Discipline & Willpower

 - Willpower by Tierney and Baumeister
 - The Power of Habit by Duhigg

* Motivation & perseverance

 Passion and perseverance for long term goals

 - [[https://www.ronaldreaganhs.org/cms/lib7/WI01001304/Centricity/Domain/187/Grit%20JPSP.pdf][Grit: Perseverance and Passion for Long-Term Goals]] |
   Angela Duckworth 2007 (article)
 - [[id:duckworth:2007grit][Grit: Perseverance and Passion for Long-Term Goals]] |
   Angela Duckworth 2016 (book)


 - [[https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance][Grit: The power of passion and perseverance]] | TED Talk
 - [[http://angeladuckworth.com/grit-scale/][Grit Assessment]] | Survey Quiz
  

2.) For an adaptive/active mindset (and recovering from failure)

 - Mindset by Carol Dweck
 - Apapt by Tim Harford

