
* Trivium Notes

Most of this material will be moved into other files....

  - Mastery: George Leonard
  - Mastery: Robert Greene

------

The Primium, Trivium and Quadrivium (PTQ) are not only cumulative,
building each on the the other, but they are also iterative, in that
they are studies that will continue through one's entire life.

We study different things, at different levels of complexity as they
are mastered.  There is so much accumulated knowledge and
specialization that no one will ever master everything.  So the
/Primium/ is not only only for >11 age children.  Even if you are 200
years old, you might still want to master a new language and will
do this at the level of the Primium.  This is not to say that people
who have mastered the Trivium and Quadrivium will study a new language
in the same way that a 7 year old will because the 7 year old will not
have the ability to grasp abstractions and complexity.  So there will
be two Primium tracks, one for children under the age of 11, and one
for learners who have already completed the first stage of the
Trivium.

* The Nature of Education
** Primium
 :: Scope

*** Intro

**** Primary Education

Two tracks:

   child is born into a contemporary native english speaking society
   and english is their native language.

or

   child was born into a contemporary society where english is not
   spoken or spoken as a second language

The Primium (latin for /first/) is the minimum skills and knowledge a
student must master before she can study the Trivium.

This includes basic:

  - spoken english  :: basic fluency
  - written english :: remedial
  - reading level :: remedial
  - arithmetic :: numbers, addition, subtraction, multiplication, division
  - world geography :: continents, seas, countries, rivers etc.
  - computer :: basics of a gui os, web browser & text editor.

The Primium can be started as early as two years old, and the more
that the child is able to memorize and practice the better.  But no
complex reasoning or abstract concepts should be taught before the
child turns ten or eleven.

** Trivium
 :: Scope

*** Intro
the tools needed to study the quadrivium

  - Grammar  :: symbol systems to communicate and manipulate langauge
    - written language -- tools to express written language - chalk,
      ink and bits.  
    - reading :: 4 kinds
    - etymology :: history & conext of words
    - history :: time as narratives 
      - process philosophy
      - oral, written & code traditions
    - number :: 
    - code :: dynamic manipulation of text (everything is text)
    - maps :: spatial symbol systems
    - bitmaps :: images / video
    - geometry / vectors :: 
    - audio ::    
  - Logic    ::
    - analytical and synoptic reading
  - Rhetoric :: communication
    - composition
    - communication
    
The Trivium should be started at the age of 11, no earlier.  At this
age the child is able to begin to comprehend complex and abstract
concepts.

The Trivium provides the child with the intellectual tools to express
thoughts in spoken, written and code form, communicate with others,
and to think rationally and critically.

These arts will be a foundation that the child will be able use the
rest of their lives and form the basis for self-directed and directed
study in the future.

**** Subjects included

- history
- literature
- 

*** Grammar
*** Logic
*** Rhetoric
** Quadrivium
 :: Scope

The original Quadrivium was made up of four subjects that each dealt
with different aspects of number and magnitude: arithmetic, geometry,
music and astronomy.  This originated with Plato's belief that the
Universe could best be understood in terms of number.

Our understanding of how the world works is far more complex and
nuanced today.  And even though in recent years the idea that we live
in a /mathematical universe/ has brought us full circle back to Plato
in some respects, mathematics is still removed from physical reality
and from mind.  Mathematics is very good at modeling the universe, but
the universe is better unstood in terms of information.  Information
is a gray area that sits somewhere between mathematics and the
physical universe.  Information is directly connected to the physical
universe, it requires energy to create and destroy it.  And
increasingly information is being seen as the basic building block of
the universe -- everything in the universe, space, matter and energy
can be thought of as actualized information.  As if information was a
computer program, that compiles into matter, energy and space.

The new Quadrivium is made up of four subject that deal with different
aspects of information; mimesis, rhizomata, systema and transacta.
 
*** Mimesis
*** Rhizomata
*** Systema
*** Transacta

* b>i notes

** Studyhall: A Lifetime Learning Program

Since the beginnings of what would become the modern college or
university in medieval Europe, learning has always been thought of as
a place.  You go to a /place/ to learn, study and then after passing
examinations and other requirements a student is granted a /degree/
certificate that certifies that the person has completed and mastered
the materials in their course of study.  Until recently, this was the 
end of most people's education.  What was learned would be adequate to
support a career that would last the rest of a person's active working
life. 

This model worked well when the rate of innovation in a society
happened at a steady and relatively slow pace that could be measured
in decades and generations.  But this is no longer the case today.
Change is happening in months and years that might have taken
centuries in the past.  Higher educational institutions can not keep
up with this rate of change, and by the time they have identified new
technologies and bodies of knowledge that should be taught, and
designed courses to teach this to students, the technology is already
far behind what is being used in mainstream business and research.

Learning must change from being in a specific /place/ one goes for a
set /duration/ to learn something to a /process/ that is happening all
of the time, no matter where you are.

Such education will be a combination of traditional /place-based/
education, /directed self-study/, and /learning-by-doing/ by working
with people who have already mastered and actively practiced within a
discipline.

*** Directed Self Study

Self-study is difficult and often seen as inferior to studying in a
traditional educational program.  In one sense this is 

, mostly because there is a lack of meaningful feedback and
reinforcement.

*** Stages of Learning

Rather than thinking in terms of a person being an expert or master in
general, we need to change our thinking to acknowledge that just
because you are a master of one subject, you will be, at best,
beginner in most other subjects.

We all go through the same stages of learning, throughout our lives,
with different levels of mastery in different domains.  Winning the
noble prize in Biology does not mean that you even as qualified as a
first year student studying economics or literature.

We break down these stages as:

  - novice :: a beginner who is learning the fundamental knowledge and
       skills required of a given discipline.
  - apprentice :: an advanced beginner who has learned enough to be
       able to productively work together with people who have mastered
       the discipline.  It is as an apprentice that you commit to
       actively practicing a discipline with the goal of eventually
       mastering it.
  - jack :: a person who has mastered a discipline, but has still not
       practiced it long enough to be a master in their own right.
       Jacks are expected to spend time working on different projects
       with different teams to deepen and expand their mastery of
       their discipline.
  - master :: one who practices their discipline not as a means of
       learning what others have done before them, but learning as a
       means of expanding and extending their discipline and knowledge
       in new ways.

We must treat these stages of learning, not as qualifications,
granting status, but instead as active /roles/ that we practice in
different aspects of our lives.  If one of your /roles/ is /a master
of particle physics/ when you are in the lab, at home your children
only see you in your role as /mom/.  We need to wear these hats with
great seriousness when we are within that role, but wear them lightly
or not at all when wearing another hat.  And we must constantly strive
to always try new hats, to always be a beginner, interested in
beginnings as a process that continues through our entire lives.

*** Trivium

*** Core Skills

Before one can even become a novice, there is a core set of knowledge
and skills that must be mastered.  In medieval europe, these core
skills were called the Trivium which was made up of three courses of
study, grammer, logic and rhetoric.  Modern use of these terms differs
from their original meaning, but in essense, the Trivium was meant to
give students the intellectual skills to learn how to learn.  More
specifically, to be able to manipulate symbol systems (math and
writing), think rationally and logically and to communicate with
others.

Echoes of the medieval Trivium can still be found in /liberal arts
degree/ programs, but the idea of building general purpose learning
skills that can be used through ones whole life were watered down
during the Industrial Revolution which required workers with fixed
skillsets that would not change much in their careers.  Today's
educational needs are a very good fit with the concept of the Trivium
by providing the skills to learn and communicate anything throughout
your working life.

We are reimagining the Trivium to equip students not only to be able
to work with written and spoken laguage and math, but programing and a
solid foundation in physics and chemistry that can be used in any
discipline. This may sound strange at first, for those who wish to
study sociology or law, but having a solid working knowledge of how
the physical world works is just as important for a poet as it is a
judge or even a politician.  Present day lawyers, judges and
politicians would be better qualified to weigh in on issues like
climate change, health issues public safety if they had a core
education which gave them the intellectual tools to see the difference
between what is real and what is possible and bullshit masquerading as
facts.

*** Apprenticeships

* Outline

This outline which is more of a reading list is based on:

  [[http://home.uchicago.edu/~rfulton/Trivium.htm][The Trivium]] | U.of Chicago Course

* THE TRIVIUM


Throughout the Middle Ages, formal education began with the study of
language: grammar, including the study of literature as well as the
practical mastery of the mechanics of language (here, Latin); logic or
dialectic, whether narrowly defined as the art of constructing arguments
or, more generally, as metaphysics, including the philosophy of mind;
and rhetoric, or the art of speaking well, whether to praise or
persuade.
 

/Martianus Capella and the Seven Liberal Arts: Vol. II  The Marriage of
Mercury and Philology/, trans. William Harris Stahl with E.L. Budge (New
York: Columbia University Press, 1992).

John of Salisbury, /The Metalogicon: A Twelfth-Century Defense of the
Verbal and Logical Arts of the Trivium/, trans. Daniel D. McGarry
(Philadelphia: Paul Dry Books, 2009).

 

All other readings available online through JSTOR, Google Books, or
Chalk.   Readings marked ﾒRegﾓ are also on reserve at the Regenstein
Library.


** Why study the /trivium/?

Dorothy Sayers, [[http://www.gbt.org/text/sayers.html][The Lost Tools of Learning]] (1947)

** Education in the Middle Ages

Lynn Thorndike, ﾒElementary and Secondary Education in the Middle Ages,ﾓ
/Speculum/ 15.4 (October 1940): 400-408 [JSTOR]

Caroline M. Barron, ﾒThe Expansion of Education in Fifteenth-Century
London,ﾓ in /The Cloister and the World: Essays in Medieval History in
Honour of Barbara Harvey/, eds. John Blair and Brian Golding (Oxford:
Clarendon Press, 1996), pp. 219-45 [Chalk]

 

Charles H. Haskins, ﾒA List of Text-Books from the Close of the Twelfth
Century,ﾓ /Harvard Studies in Classical Philology/ 20 (1909): 75-94 [JSTOR]

Alexander Nequam, A list of textbooks from /Sacerdos ad altare/, in
/Medieval Grammar and Rhetoric: Language Arts and Literary Theory, AD
300-1475/, eds. Rita Copeland and Ineke Sluiter (Oxford: Oxford
University Press, 2009), pp. 531-41 [Chalk; Reg]

 ﾒAppendix I: A Time-Table of Lectures in the Arts Course of the
University of Toulouse, 1309,ﾓ in Louis John Paetow, /The Arts Course at
Medieval Universities with Special Reference to Grammar and Rhetoric/
(Champaign, IL: 1910), pp. 95-99 [Google Books]

** January 10 The Seven Liberal Arts

Honorius Augustodunensis, ﾒConcerning the Exile of the Soul and its
Fatherland; also called, About the Arts,ﾓ in /Readings in Medieval
Rhetoric/, ed. Joseph M. Miller, Michael H. Prosser, and Thomas W.
Benson (Bloomington: Indiana University Press, 1973), pp. 198-206
[Chalk; Reg]

Henri dﾕAndeli, ﾒThe Battle of the Seven Arts,ﾓ ed. and trans. Louis
John Paetow, /Memoirs of the University of California/ 4.1, /History/
1.1 (Berkeley: University of California Press, 1914), pp. 37-60 [Chalk]

 

H. Parker, ﾒThe Seven Liberal Arts,ﾓ /The English Historical Review/
5.19 (Jul. 1890): 417-61 [JSTOR]

Karl F. Morrison, ﾒIncentives for Studying the Liberal Arts,ﾓ in /The
Seven Liberal Arts in the Middle Ages/, ed. David L. Wagner
(Bloomington: Indiana University Press, 1983), pp. 32-57 [Chalk; Reg]

 

** The Nuptials of Eloquence and Learning

Martianus Capella, /The Marriage of Mercury and Philology/, bks. I-II,
trans. Stahl, pp. 3-63 [Sem Co-op; Reg]

 

W.H. Stahl, ﾒTo a Better Understanding of Martianus Capella,ﾓ /Speculum
/40.1 (Jan. 1940): 102-115 [JSTOR]

Cora Lutz, ﾒRemigiusﾕ Ideas on the Origin of the Seven Liberal Arts,ﾓ
/Medievalia et Humanistica/ 10 (1956): 32-49 [Chalk]

Cora Lutz, ﾒRemigiusﾕ Ideas on the Classification of the Seven Liberal
Arts,ﾓ /Traditio/ 12 (1956): 65-86 [JSTOR]

 

* I. GRAMMAR
** What did Grammar teach?

Martianus Capella, /Marriage/, bk. III, trans. Stahl, pp. 64-105.

Cassiodorus, /Institutions of Divine and Secular Learning/, bk. II,
preface, trans. James W. Halporn (Liverpool: Liverpool University Press,
2004), pp. 171-78 [Chalk]

Jeffrey F. Huntsman, ﾒGrammar,ﾓ in /The Seven Liberal Arts/, ed. Wagner,
pp. 58-95 [Chalk; Reg]

** /Ars grammatica antiqua/

Aelius Donatus, /Ars Minor/, /Ars Maior/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 82-99 [Chalk; Reg]

Priscian, /Institutiones Grammaticae/ and /Institutio de Nomine
Pronomine Verbo/, in /Medieval Grammar and Rhetoric/, eds. Copeland and
Sluiter, pp. 167-89 [Chalk; Reg]

Isidore of Seville, /Etymologiae/, in /Medieval Grammar and Rhetoric/,
eds. Copeland and Sluiter, pp. 232-41 [Chalk; Reg]

Alcuin, /Ars Grammatica/, in /Medieval Grammar and Rhetoric/, eds.
Copeland and Sluiter, pp. 272-87 [Chalk; Reg]

Glosses on Priscian by Remigius and His Followers, in /Medieval Grammar
and Rhetoric/, eds. Copeland and Sluiter, pp. 299-310 [Chalk; Reg]


** Reading the classics

/Accessus ad auctores/[Introductions to the Authors], in /Medieval
Literary Theory and Criticism, c. 1100-c.1375: The Commentary
Tradition/, eds. A.J. Minnis and A.B. Scott, with David Wallace, rev.
ed. (Oxford: Clarendon Press, 1988), pp. 12-36 [Chalk]

Conrad of Hirsau, ﾒDialogue on the Authors,ﾓ in /Medieval Literary
Theory/, eds. Minnis and Scott, pp. 37-64 [Chalk]

 

** Thinking grammatically

Anselm of Canterbury, /De grammatico/, in /The Major Works/, eds. Brian
Davies and G.R. Evans (Oxford: Oxford University Press, 1998), pp.
123-50 [Chalk]

John of Salisbury, /Metalogicon/, bk. I, chaps. 13-25, trans. McGarry,
pp. 37-72 [Sem Co-op; Reg]

 

** /Ars grammatica nova/

Alexander of Villa Dei, /Doctrinale/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 573-83 [Chalk; Reg]

Eberhard of B師hune, /Graecismus/, in /Medieval Grammar and Rhetoric/,
eds. Copeland and Sluiter, pp. 584-93 [Chalk; Reg]

 

James J. Murphy, ﾒThe Teaching of Latin as a Second Language in the
Twelfth Century,ﾓ in /Latin Rhetoric and Education in the Middle Ages
and Renaissance /(Aldershot: Ashgate/Variorum, 2005), III [Chalk]

Robert Black, ﾒThe Vernacular and the Teaching of Latin in Thirteenth
and Fourteenth-Century Italy,ﾓ /Studi Medievali/, 3^rd ser. 37 (1996):
703-51 [Chalk]

Nicholas Orme, ﾒJohn Holt (d. 1504), Tudor Schoolmaster and Grammarian,ﾓ
/The Library/, 6^th ser. 18.4 (December 1996): 283-304 [Chalk]

 
* II. DIALECTIC

** What did Dialectic teach?

Martianus Capella, /Marriage/, bk. IV, trans. Stahl, pp. 106-154

Cassiodorus, /Institutions/, bk. II, chap. III, trans. Halporn, pp.
188-208 [Chalk]

 
Eleanore Stump, ﾒDialectic,ﾓ in /The Seven Liberal Arts/, ed. Wagner,
pp. 125-46 [Chalk; Reg]

 

** The Problem with Education These Days

John of Salisbury, /Metalogicon/, Prologue; bk. I, chaps. 1-12; bk. II,
chaps. 1-20; trans. McGarry, pp. 3-37, 73-141

 

** The Point of It All

John of Salisbury, /Metalogicon/, bks. III-IV, trans. McGarry, pp. 142-276

 

** Applied Dialectic: Universals and Particulars

Aristotle, Porphyry, Boethius, Garlandus Compotista, and Abelard, in
/Basic Issues in Medieval Philosophy/, eds. Bosley and Tweedale, Topic
VI, pp. 352-92 [Chalk]

John of Salisbury, /Metalogicon/, bk. II, chaps. 17-20; bk. III, chaps.
1-4; trans. McGarry, pp. 111-41, 146-70

* III. RHETORIC


** What did Rhetoric teach?

Martianus Capella, /Marriage/, bk. V, trans. Stahl, pp. 155-214

Cassiodorus, /Institutions/, bk. II, chap. II, trans. Halporn, pp.
178-88 [Chalk]


Martin Camargo, ﾒRhetoric,ﾓ in /The Seven Liberal Arts/, ed. Wagner, pp.
96-124 [Chalk]

 

** /Rhetorica christiana/

Augustine of Hippo, /On Christian Doctrine/, bk. IV, trans. J.F. Shaw,
pp. 154-203 [CCEL http://www.ccel.org/a/augustine/doctrine/]

Bede, /De schematibus et tropis/ [ﾒConcerning Figures and Tropesﾓ],
trans. Gussie Hecht Tannenhaus, in /Readings in Medieval Rhetoric/, eds.
Miller et al., pp. 96-122 [Chalk; Reg]

 
** /Ars poetica/

Matthew of Vend冦e, /Ars versificatoria/ [/The Art of Versification/],
trans. Aubrey E. Galyon (Ames: Iowa State University Press, 1980), pp.
25-112 [Chalk]

Geoffrey of Vinsauf, /Poetria nova/, trans. Margaret F. Nims (Toronto:
Pontifical Institute of Mediaeval Studies, 1967), pp. 15-93 [Chalk]

** /Ars dictaminis/

John of Garland, /Parisiana poetria/, ed. and trans. Traugott Lawler
(New Haven: Yale University Press, 1974), chaps. 1-4, 7, pp. 3-83,
143-59 (odd numbered pages) [Chalk]

Anonymous of Bologna, /Rationes dictandi/ [/The Principles of
Letter-Writing/], trans. James J. Murphy, in /Three Medieval Rhetorical
Arts/, ed. James J. Murphy (Berkeley and Los Angeles: University of
California Press, 1971), pp. 3-25 [Chalk; Reg]


** /Ars praedicandi/

Thomas of Chobham, /Summa de arte praedicandi/, in /Medieval Grammar and
Rhetoric/, eds. Copeland and Sluiter, pp. 614-38 [Chalk; Reg]

Robert of Basevorn, /Forma praedicandi/ [/The Form of Preaching/],
trans. Leopold Krul, O.S.B., in /Three Medieval Rhetorical Arts/, ed.
Murphy, pp. 111-215 [Chalk; Reg]


 

