#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to the Trivium
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-introduction.org
  :Created: 2017-02-13T12:32@Prek Leap (11.642600N-104.919210W)
  :ID: 3485b3fc-3c51-4459-847c-462b7a5d040f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

Searching for the word 'Trivium' results in a short list of
results, with a terse article in Wikipedia, Dorothy Sayer's
famous essay and Sister Mirium Joseph's book that is
deservedly called a classic.  Beyond that there are variety
of essays and a few books that call themselves variations on
'the new trivium'.  A few are well researched and thought
out.  Most, including not a few papers in peer reviewed
academic journals are decidedly not.

The worst offenders seem to be from academics who propose
educational reform from within.  The present educational
system (to be generous) has the Trivium and Quadrivium as
it's ancient ancestors.  There are vestiges of the original
system, but often they are little more than labels which
survived the centuries.

I am not suggesting that that the medieval educational
system be resurrected as a 21st century solution. 

But there is an argument to be made that in some respects we
are transitioning from the Industrial Revolution which
required a docile workforce with minimal literacy and math
skills who will do what they are told, sit or stand in place
all day every day and do mindless repetitive tasks.  In
other words, the industrial revolution turned humans into
single-task machines, discarding all sorts of skills that
humans had evolved to adapt, improvise and deal with
uncertainty.  In return they were told that the would have
perfect certainty and security.  Gone were the craftsmen,
the artisans, the master builders, the small landholders
whose families knew the land they cultivated through
countless of generations as an extension of themselves.

Don't get me wrong, there is no romantic utopian past I am
advocating we return to.  Those past ages were also 
ignorant, dirty, pestilent shit holes.  Life was short,
painful and cruel.

But the industrial revolution is peetering out.  Ford's
assembly line, leveraged information to standardize and
create economies of scale.  But while our ability to
manipulate matter was improving -- our ability to create
machines and control those machines was crude.  And most of
this was because our ability to collect and process
information was even cruder.

This is no longer the case, and the miracle of the assembly
line and industrial processes no longer need to be done at
scale to achieve the same economies of scale.  Our ability
to leverage information is making industrial economies
increasingly distributed and federated.  And over the coming
decades this shift will displace and replace traditional
industrial civilization from soup to nuts.

For this to happen, we will need a corresponding revolution
in education -- and abandon modern school methodoligies
which are largely modeled on industrial systems.

In its place we need people who can think -- who never stop
learning (school is no longer a place, like a factory where
you go to learn) and learn how to learn, and think logically
and rationally and communicate and collaborate effectively
with other people and the info-mechanical infrastructure
that replaced the industrial world that was still in place
less than a generation before.

As olson said, man has become estranged from his true nature
-- and perhaps, with a bit of luck, this turn of the screw
could improve the human condition, rather than leave it
materially better off (from the industrial revolution) while
alienating and destroying our connection to the world in
which we live.  Perhaps, just perhaps we can reconnect with
the world and our place in the universe and be happy and
comfortable to be part of it again.

Relearning to think and reason is a good beginning.

---

Keep in mind that this not the Medieval Trivium, though much
has been borrowed from it, including a lot of
nomenclature. It would be better to call this the /Scopic
Trivium/.  We will learn more about Scopic Philosophy later
in this introduction.

The Medieval Trivium was the equivilent of a modern College
or University Bachelor's Degree.  And the Medievel Trivium
is still the ancient ancestor of the Liberal Arts Bachelor's
degree program, though one must often squint with just the
right amount of grimmace to see it at times.


---

There is no small amount of tension in the Trivium between
Grammar, Dialectice and Rhetoric.  Each is a very different
way of understanding the world, relating to it,
communicating with each other about it, and figuring out
what it means.

#+begin_quote
The three arts of the trivium challenge because they are,
fundamentally, different ways of seeing the world. Just as I
saw Stanislavski, Artaud, and Brecht as seeing truth in
fundamentally different ways, so do the three arts. It would
be far easier to be a grammarian, a dialectician, or a
rhetorician rather than being an advocate for the trivium,
because such an advocacy requires embracing contradictions
and living with uncertainty, even paradox.

Although some teachers want politics out of education, we
need to note that education is essentially a political act,
as is parenting. Do we want our children to be just like us,
or do we want them to be different and thus end up
challenging us? This uneasy relationship between control and
freedom is played out in every nation, every classroom, and
every home. This tension is implicit in the relationship
between grammar, dialectic, and rhetoric.

-- Trivium 21 Century
#+end_quote

In a way it's amazing that it held together at all, for so
long, with all three splitting in a very messy divorce will
all parties claiming that they keep the children...

But again, (as I note later) that a lot of this tension is
when there is a major shift in how we do things.

In the time of Plato, that was the shift from the oral to
the written tradition -- in the medieval europe it was
moveable type and Gutenberg Press -- in the 19th and 20th
centuries it was mass media and universal literacy and now
in the 20th century it is the troika of digitization of
text, video and audio; providing anyone of even modest means
with the ability to create and publish information at levels
that was reserved only for media tycoons and heads of state
less than 50 years before, and now, the the unimaginable
centralization of communication channels that determine how
these tools are used, and used against us.

I have a bit of a beef with Platonic forms in any case.
In process philosophy, everything is in the process of
becoming something else.  So when does the platonic form for
a bird come from?  When did dinosaurs stop being dinosaurs
and became birds?  Can something embody multiple ideal forms?
It would seem that this drags in the need for an observer as
well.  Plato would argue that no observer is necessary
because each bird is a shadow of the perfect bird form.  And
how do these forms come into existence?  If forms are
eternal, that implies that the bird form existed from the
big bang for billions of years up until the bird evolved
from the dinosaur.  Does that mean that the forms for all
future creatures and categories exist as well?  Or is the
world of forms a kind of ideal Everett Universe that
contains all possible forms that result from causal-chains?
And what of the imagination.  There is certainly no such
thing as a hobbit, dragon or a unicorn, but for there must
be a platonic form for each of them, in order for people to
be able to understand what a hobbit is.  Then there are
misconceptions, beliefs and dieties.  If monotheists believe
there is a single all powerful god, then is there too a
platonic form for that god, and did that form preceed god's
existence, or determine what form god would take?  Once you
even peek down these rabbit holes forms become far more
cumbersome as a concept than they are worth.  Like the
existence of the  æther, which was thought to be a universal
medium through which allowed light and gravity to travel in
a vacuum, the plato's world of forms is simply not needed.

Does this mean I am advocating an Aristotelian view?

#+begin_quote
The grammarian will tell it like it is, either by agreed
practice or imposed rules; the Socratic dialectician will
ask about it until it is no longer; the Platonic
dialectician will discuss it until ‘ultimate truth’ is
revealed; and the Aristotelian dialectician will use an
approach that should uncover possible truths with differing
degrees of probability.

-- Trivium 21 Century
#+end_quote

This, of course is a gross simplification -- but if these
are the options available, Aristotle provides a better match
to inductive empirical reality.

I can't shake the feeling through, that Aristotle was no
less comfortable with uncertainty than Plato -- Logic is an
enormously powerful tool -- but I wonder how satisfied
Aristotle was with it?  Embracing uncertainty, while still
demanding that we take all possible measures to minimize
uncertainty is on face contradictory, to have a goal which
you must work tirelessly to work towards, but still feel
comfortable knowing that the goal is impossible to achieve.
That truth is a horizon relative to the observer, and that
one can never reach it, only extend that horizon seemingly
forever.  Worse still, is that the horizon receeds before us
and behind us, in space and time.  No matter how large a
number is, you can always add another number to it.
Infinity rightly scares the crap out of most people who
think about it too long.  Which is why anyone who finds the
the concept of an eternal soul comforting, both as reward or
punishment has not really thought it through.  An eternal
heaven is nearly as terrifying as an eternal hell.  Even the
Universe is not eternal -- because it had a beginning,
though the end escapes us at the moment.  But infinity
dwarfs even this, because anything with a beginning can be
added to.  The second before the big bang... there is simply
no end to it.  But more likely, we simply have not yet
extended our minds and miserable senses enough to see, not
astute enough to perceive, not wise enough to understand...



* Scopic Philosophy

It was really only recently that I realized that my relentlessly
evolving concept of Scope had become— while I was not watching—a
philosophy in its own right.

Every Civilization is built on philosophical tradtions that contain
many variations over time and location, but like in Jazz
improvisation, still manage to stay within the theme set at the
beginning.  The Western Tradition that Western Civilization is based
on Greek/Roman tradition.  If there is an Eastern Tradition, it could
be argued that it is based originally on Hindu mytholody and was later
refined into Buddhist/Confucian Tradation.   

It is my belief that a new Tradition will need to be established in
order for a truly distributed, /solar civlization/ to be possible that
reflects the fundemental change that mankind is undergoing that is
redefining its relationship to nature and the universe.

This is not to say that Scopic Philosophy will be the foundation for
/anything/, let along the foundation an underpinning Tradition for a
civilizaion, but I do hope that it will be useful for those who do.

** Components

Scopic Philosophy is modular in that it provides a framework for
understanding how the world works.  But it can also be combined with
any number of classical philosophies of life.  It works extremely well
in combination with Skepticism and Epicureanism.

  - Reconciles Atomist and Holistic views of the World.
  - A concept of Time and Causality based on Process Philosophy
  - A Temporal Model based Scope (Context: LOD, POV ROC)
  - A Dynamicly Changing Cosmology that reflects the current scientic consensus
    of how the Universe works based on the scientific method.
  - Plug-in Philosophy of Life
  - Plug-in Phlosophy of lifelong learning.

* Learning -- onion

think of learning as something akin to the human brain which
is made up in successive layers -- with the reptilian brain
at the core, and eventually adding the limbic system and
finally the neocortex

It's important that knowledge is taught as if it is an onion
that is builds layer apon layer until reaching the present
state of knowledge at the outside which can then be the
basis for building new layers.

Knowing how we have come to know something is important
because it includes all of the blind alleys and walls that
we kept running up against before finally surmounting them
to build up the next layer of the onion.  The history of
knowledge is all about how to build better mousetraps by
first knowing all of the past mousetraps that have been
devised in the past, and how they have worked or not....

* Learning -- disciplines


The mechanical arts were outside of the quadrivium, a rift
that is still with us today

the thing is, we need to stop thinking in terms of
disciplines and rather think in terms of holons and how
cultures (disciplines) look from inside the discipline and
from without.

we also need to start thinking of everything being an
extension of our senses, muscles and neocortex -- there is
nothing that is done for its own sake, at least not if it's
any good or of any use -- beauty is important, in fact it is
critical to our survival -- the decorative arts are also
critical, because they center us where we are and put us in
context with the world around us -- they are an anchor --
when done right (which is rare today)

* Scopic Trivium

can't separate trivium from Latin -- this is important,
because we will be teaching english as a foriegn lanaguage,
even to native speakers -- it will be a very specific
language designed to bridge generations and linguistic drift
so that texts will remain in use over very long time frames.

This will be especially important for scientific papers and
cannonical works -- and translation of older english works
into scopic english will have to be undertaken -- or at the
least that editions are presented that provide glossa and
scholia that define anything that falls outside of Scopic
vocabulary and usage.

This will especially be important for technical terms --
which go in and out of vogue far more often than might be
thought....

The Scopic Trivium this will include:

   - english (a defined subset that will change slower than the
     vernacular)
   - scopic a DSL (domain-specific-language)
   - incantation script (based on CJK)


* Truth

Aristotle's set of basic axioms from which he derived the
rest of his logical system:

   - An object is what it is (Law of Identity)
   - No statement can be both true and false (Law of
     Non-contradiction)
   - Every statement is either true or false (Law of the
     Excluded Middle)

This is the foundation for all of logic!  And here I am
throwing a spanner into the works and saying that these
three things are true and not true in a fnord because this
is how things are in nature as well -- in quantum mechanics
both states exist until it has been observed.

  The Cat Is Alive
  The Cat Is Dead

are both true statements until you peek into the box.

As I write this, the United States is in a crises, largely
because over the past 30 years the Rebpublican Party has
decided that they can lie about anything and everything and
people will believe them, and there won't be any serious
consequences.  They were able to keep that up for a long
time and the lies became bolder and the actions that they
justified by using those lies got to the point where a lot
of people lost the ability to tell facts from lies.  And
those people elected president, a moron who actually
believes tabloid papers like the National Enquirer are valid
sources of reliable information.  Even after being elected,
and having at his personal disposal an intelligence state
whose only job is to spend hundreds of billions of dollars
to find out what is happening and if it is true or not,
ignores the professionals and continues to use tabloid press
as credible intelligence.

But no matter how bad this gets, it's important to
understand that this is still an outlier, a thirty year
outlier, but still an outlier.

#+begin_quote
...excessive focus on things like vaccine denialists teaches
the wrong habits. It’s a desire to take a degenerate case,
the rare situation where one side is obviously right and the
other bizarrely wrong, and make it into the flagship example
for modeling all human disagreement. Imagine a theory of
jurisprudence designed only to smack down sovereign
citizens, or a government pro-innovation policy based
entirely on warning inventors against perpetual motion
machines.

-- [[https://slatestarcodex.com/2017/03/24/guided-by-the-beauty-of-our-weapons/][Guided By The Beauty Of Our Weapons]] | Slate Star Codex
#+end_quote

But this is not simply a matter of a percentage of the
population that insists on believing things which are
patently untrue, it is compounded by Social Media, who has
been telling everyone that their opinion is important, just
as important any any /expert/.  And then give everyone a
platform where /everyone/ is an expert, everyone is a leader
and that no matter how stupid or wrong their opinions are,
they are valid.

#+begin_quote
Everyone from statisticians to Brexiteers knows that they
are right. The only remaining problem is how to convince
others. Go on Facebook and you will find a million people
with a million different opinions, each confident in her own
judgment, each zealously devoted to informing everyone else.

Imagine a classroom where everyone believes they’re the
teacher and everyone else is students. They all fight each
other for space at the blackboard, give lectures that nobody
listens to, assign homework that nobody does. When everyone
gets abysmal test scores, one of the teachers has an idea: I
need a more engaging curriculum. Sure. That’ll help.

-- [[https://slatestarcodex.com/2017/03/24/guided-by-the-beauty-of-our-weapons/][Guided By The Beauty Of Our Weapons]] | Slate Star Codex
#+end_quote

Before social media and the Internet there were many groups
of people who believed stupid things, but these things
happened in the Fashion Layer, the slower moving
Institutional and Culturals layers would eventually level
things out and bring things back into line.  But as the
institutions that form the infrastructure for the Nation
State strain under the immense load of information resulting
by ever increasing rates of change, the Fashion layer is
teetering on the brink of being cut adrift of the other
layers.  When this happens, it is usually a precurser to a
collapse.

But of course it's more complicated than that because the
educational system that was established in the early 20th
century was designed to train and indoctrinate factory
workers who needed remedial literacy skills and would do
what they were told.

Just as the first computers were humans, the first robots
were humans too.  Slaves were the proto-form of the factory
worker on an assembly line.  Who needed the extra burden of
providing food and shelter for slaves when factory workers
could be got on demand, and could be discarded far easier
than slaves.

So the Internet was dumped into the laps of a population who
never had had any real choice, was used to being told what
to do, and how to spend whatever money they could make on
things that they produced in the factories.

But the internet is not the same as mass media -- couch
potatos sit and let information wash over them, with bits
here and there actually penetrating into consciousness.

The Internet gave people far more responsibility than they
could cope with.  News and media have always been maps to
guide people through their lives, but when everyone is a
news and media provider, the map becomes the territory and
becomes disfunctional.

The industrial revolution reduced the Trivium to only
Grammar, discarding Dialectic and Rhetoric which those in
power didn't want the great unwashed masses to have access
to.  So they told people what information was important and
then told them to be a good consumer and buy stuff that will
make you happy.

Dialectic and Rhetoric were limited to those working in
news, media and academic institutions.  So when everyone
joined facebook and twitter, they simply didn't have the
intellectual tools to figure out what is true or not, or how
to communicate and convince others of what they have found.
Instead Social Media has just become another place to waste
time replacing sitcoms on broadcast television.  People
weren't ready to deal with the contradictions, and paradoxes
and uncertainty they were being asked to cope with.

The present generation or two is likely lost, people can
only change so much over a lifetime and what we are asking
of people is beyond the cognitive capability for most
people.  I am /not/ saying these people are dumb, but they
were dealt a shitty hand.  This has happened over and over
throughout history, and there has never been a recorded
instance where the majority of these doomed generations are
able to escape their fate.

This doesn't mean we don't try to reach as many people as
possible, even as we rethink what it means to have the
minimal education in a technologically advanced civilization
in order to live a productive and meaningful life.

* Trivium
 

Need to think about the trivium in context with Havelock's
idea of pre-literate modes of thought.  The heavy emphasis
in the trivium on rhetoric as a tool for oratory is solidly
grounded in, the spoken word -- something that we shifted
away from in the modern era -- mass education, and universal
literacy shifted the role of oratory dramatically sometime
towards the end of the 70's -- the tipping point happened
and no one seemed to notice.

We are living in a post-oral world -- which oddly coincides
with a post-literate segmentation of society which places
less importance on the written word, and instead gravitates
towards produced multi-media that seems to attempt to
bi-pass rationality and logic all together and appeal
directly to the emotions that are adrift in a contextless
cloud that swings often violently between desires and fears.
Not only is there no context -- there is no stability,
shifting sands beneath out feet.  This condition is well
known to those in power, in government, religion, and
industry and are used against us, as a tool of control,
which runs diametrically opposite to the role that human
institutions are supposed to provide.  The culture, layer
has been turned against us -- subverting institutions to
make us more afraid, to make descision that are not in our
self interest, and only serve to enrich an elite who are
trapped in their own bubble of desire, fear and hunger for
power and status.  This is why people no longer trust
institutions to provide truth, or justice, or even a living
wage.

** Intro
the tools needed to study the quadrivium

  - Grammar  :: symbol systems to communicate and manipulate langauge
    - written language -- tools to express written language - chalk,
      ink and bits.  
    - reading :: 4 kinds
    - etymology :: history & conext of words
    - history :: time as narratives 
      - process philosophy
      - oral, written & code traditions
    - number :: 
    - code :: dynamic manipulation of text (everything is text)
    - maps :: spatial symbol systems
    - bitmaps :: images / video
    - geometry / vectors :: 
    - audio ::    
  - Logic    ::
    - analytical and synoptic reading
  - Rhetoric :: communication
    - composition
    - communication
    
The Trivium should be started at the age of 11, no earlier.  At this
age the child is able to begin to comprehend complex and abstract
concepts.

The Trivium provides the child with the intellectual tools to express
thoughts in spoken, written and code form, communicate with others,
and to think rationally and critically.

These arts will be a foundation that the child will be able use the
rest of their lives and form the basis for self-directed and directed
study in the future.

**** Subjects included

- history
- literature
- 

** Grammar

#+begin_quote
Religions and leaders, however, soon saw the potential of
writing and used it to help establish their own mythology
and rules. It was clear that the written word had power; due
to its permanence it had become a symbol of authority. This
meant that rules could become fixed; something is more
difficult to challenge when it is written down. The
accountants, bureaucrats, pedantic rule makers,
authoritarians, and religious zealots were all early
adopters of written language; the poets, dramatists,
philosophers, novelists, and journalists were laggards. This
monstrous conclusion perhaps could explain the problems that
many have with the study of grammar. It is not that it isn’t
needed and doesn’t exist in our utterances, but that the way
it is taught – its rules and perceived lack of flexibility –
is authoritarian.

-- Trivium 21 Century
#+end_quote


But learning by rote -- rules, drills, and endless lists of
vocabulary is boring but it lies at the heary of practice
and mastery -- of rewiring your brain.  It takes time, it's
not pleasant -- it's hard work damn it!  

Grammar became the foundation of the Trivium because it
provided the scaffolding that makes everything else
possible.  Communication, art, beauty, drama, commerce,
betrayal, and profundity all require that all parties who
talk to each other share common knowledge between them that
makes utterances comprehensible -- we all have to be on the
same page, speaking the same language -- literally and
figuratively to exchange information -- it not, it's just
unintelligible noise.  This is what grammar provides us.

But it's important to understand that the rules of language
is only the tip of the iceberg here.  As Tolkien said, you
can't have language without an underlying mythology.
Societies are built on rules of behavior, stories, and ways
of structring things in a way that everyone in the group can
understand. 

The other role of grammar is continuity -- after all writing
is a tool for time travel -- it is grammar that ensures that
things get remembered in standardized ways that can be
passed on to future generations -- not just the next
generation, but to leapfrog generations to talk directly to
distant future descendents who only know of you from the
words that have been written and preserved through the
centuries or millennia.


** Dialectic

#+begin_quote
Man, being the servant and interpreter of Nature, can do and
understand so much and so much only as he has observed in
fact or in thought about the order of Nature: beyond this he
neither knows anything nor can do anything [p. 47].

-- Francis Bacon
#+end_quote

Dialectic in the Trivium has later been characterized as
logic, especially aristotelian logic.  But it is better
thought of as a dialectic -- an exchange of questions and
answers that is meant to come to some kind of truth.

In fact dialectic has been called not just logic, but logos
as well.  Logos is a slippery word which has changed in
meaning over time.  Christians define it as sort of
"universal truths" from God but it also simply means /word/.

It is the dialectic that questions the authority of grammar,
it keeps grammar honest, and keeps moving the goalpost, by
always taking facts and putting them into new contexts, that
may or may not result in new facts, or discovery of
falsehoods.  The dialectic keeps grammar from fossilizing...

To modern ears, logic seems to make a lot more sense -- but
isn't the inductive empirical scientific method just that?
Putting questions to things, making observations (which
answer back) that results in new understandings of the
world?

It's too easy to label the dialectic as simply the Socratic
Method, that's is only a small part of it.  Sure, you're
subjected to it in Harvard Law School -- though the
teachers, if the film, The Paper Chase is any indication,
are really hardcore grammerian's in dialectical clothing....

but if this is at the heart of the scientific method and
pretty much the foundation of our civilization, then it is
pretty damn important.

The thing is, the dialectic is messy, it embraces
uncertainty, complexity and contradiction -- it's not neat
and orderly and tied up with a bow like grammar.  And it's
not dolled up on the podium spouting or bellowing or doing
whatever it takes to convince -- rhetoric and grammar has an
agenda which is based on certainty.  Dialectic just smiles
and reminds us that we're talking out our asses.

So dialectic is a process that embraces uncertainty and
leads to truth.  But is that truth or TRUTH?  How can
questions lead us to what is true -- or put in another way,
help us to know what is real or not?

Are there higher truths -- Logos?  Is truth hierarchical,
with some truths truthier than others?  Plato certainly
thought so -- in fact he concocted the whole world of forms
and tacked it onto dialectic to make it work.

But truth doesn't exist in nature -- it's a label humans use
to understand the world.  There is just the world and the
world just is.  It's our brains which are constantly taking
in raw sensory data and trying to make sense of it -- by
establishing limits on things -- a chair is a chair because
of all the things it is not.  A chair is not a spoon or a
duck or a cheese burger.  We are constantly trying to find
the sculpture inside the block of marble.  The world is a
block of marble -- it's only us who try to make distinctions
of which part of the block are what.  So in that sense, no,
there is no higher or greater truth -- because if you take
away the brain trying to impose order on the world, the
world keeps going on happily without us, because there is
nothing trying to do this except us -- a side effect of
certain types of Life.

This is not to say that truth is not important -- without it
we die.  Figuring out what is true and false, fact and
fiction, real or illusion determines if we survive or not.
So yes, dialectic is vitally, critically important.  And
every time someone willfully lies -- it puts us all in very
real mortal danger.

---

cultural relativists, along with deconstructionist nihilism
have made a fucking mess of things.  not everything is
relative -- not everything is interpretation -- when you
have been burned by a lit match, your opinion on the burn will
not change the back that a chemical reaction released enough
concentrated heat to cook your flesh

but what are those limits?  in a nutshell, possible causal
chains of events, and which side of a holon one is observing
something from -- is it inside looking out, or outside
looking in.


** Rhetoric

Rhetoric as a subject of study seems to be nearly extinct


Look at oratory 

  - Gettysburg Address
  - Winsten Churchill
  - I Have A Dream
  - JFK Moon Speech

and then.... well nothing, even the so-called 'Great
Communicator' Ronald Reagen left nothing in our collective
memories except that people liked what he said. 
* Dorothy Sayers

Dorothy Sayers' well known essay /The Lost Tools of
Learning/ is interesting in many respects -- I especially
like how she maps the Trivium into childhood cognitive
development.

   | poll-parrot |  9-11 | grammar   | route learning   |
   | pert        | 12-14 | dialectic | questioning      |
   | poetic      | 14-16 | rhetoric  | onset of puberty |

There are some wonderful insights to be certain, but she
seems to fail to see that contradictions between grammar,
dialectic and rhetoric -- and it is these contradictions
which are the Trivium's greatest strength -- the Trivium is
a toolbox -- that produce different results and are to be
used in different ways.  But they also comprise very
different ways of understanding the world which can't be
reduced to grammar as being primarily for route-learning,
even though route learning is grammar's core methodology.

#+begin_quote
Has it ever struck you as odd, or unfortunate, that today,
when the proportion of literacy throughout Western Europe is
higher than it has ever been, people should have become
susceptible to the influence of advertisement and mass
propaganda to an extent hitherto unheard of and unimagined?
Do you put this down to the mere mechanical fact that the
press and the radio and so on have made propaganda much
easier to distribute over a wide area? Or do you sometimes
have an uneasy suspicion that the product of modern
educational methods is less good than he or she might be at
disentangling fact from opinion and the proven from the
plausible?

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote


#+begin_quote
Do you often come across people for whom, all their lives, a
"subject" remains a "subject," divided by watertight
bulkheads from all other "subjects," so that they experience
very great difficulty in making an immediate mental
connection between let us say, algebra and detective
fiction, sewage disposal and the price of salmon--or, more
generally, between such spheres of knowledge as philosophy
and economics, or chemistry and art?

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote


#+begin_quote
Another quotation from the same issue of the TLS comes in
fittingly here to wind up this random collection of disquieting
thoughts--this time from a review of Sir Richard Livingstone's
"Some Tasks for Education": "More than once the reader is
reminded of the value of an intensive study of at least one
subject, so as to learn Tthe meaning of knowledge' and what
precision and persistence is needed to attain it. Yet there is
elsewhere full recognition of the distressing fact that a man may
be master in one field and show no better judgement than his
neighbor anywhere else; he remembers what he has learnt, but
forgets altogether how he learned it."
I would draw your attention particularly to that last sentence,
which offers an explanation of what the writer rightly calls the
"distressing fact" that the intellectual skills bestowed upon us by
our education are not readily transferable to subjects other than
those in which we acquired them: "he remembers what he has
learnt, but forgets altogether how he learned it."

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote

#+begin_quote
Is not the great defect of our education today--a defect
traceable through all the disquieting symptoms of trouble
that I have mentioned--that although we often succeed in
teaching our pupils "subjects," we fail lamentably on the
whole in teaching them how to think: they learn everything,
except the art of learning. It is as though we had taught a
child, mechanically and by rule of thumb, to play "The
Harmonious Blacksmith" upon the piano, but had never taught
him the scale or how to read music; so that, having
memorized "The Harmonious Blacksmith," he still had not the
faintest notion how to proceed from that to tackle "The Last
Rose of Summer." Why do I say, "as though"? In certain of
the arts and crafts, we sometimes do precisely
this--requiring a child to "express himself" in paint before
we teach him how to handle the colors and the brush.  There
is a school of thought which believes this to be the right
way to set about the job. But observe: it is not the way in
which a trained craftsman will go about to teach himself a
new medium. He, having learned by experience the best way to
economize labor and take the thing by the right end, will
start off by doodling about on an odd piece of material, in
order to "give himself the feel of the tool."

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote

#+begin_quote
For we let our young men and women go out unarmed, in a day
when armor was never so necessary. By teaching them all to
read, we have left them at the mercy of the printed word. By
the invention of the film and the radio, we have made
certain that no aversion to reading shall secure them from
the incessant battery of words, words, words. They do not
know what the words mean; they do not know how to ward them
off or blunt their edge or fling them back; they are a prey
to words in their emotions instead of being the masters of
them in their intellects.  We who were scandalized in 1940
when men were sent to fight armored tanks with rifles, are
not scandalized when young men and women are sent into the
world to fight massed propaganda with a smattering of
"subjects"; and when whole classes and whole nations become
hypnotized by the arts of the spell binder, we have the
impudence to be astonished. We dole out lip-service to the
importance of education--lip- service and, just
occasionally, a little grant of money; we postpone the
school- leaving age, and plan to build bigger and better
schools; the teachers slave conscientiously in and out of
school hours; and yet, as I believe, all this devoted effort
is largely frustrated, because we have lost the tools of
learning, and in their absence can only make a botched and
piecemeal job of it.

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote

#+begin_quote
It would be well, I think, that each pupil should learn to
do one, or two, subjects really well, while taking a few
classes in subsidiary subjects so as to keep his mind open
to the inter- relations of all knowledge. Indeed, at this
stage, our difficulty will be to keep "subjects" apart; for
Dialectic will have shown all branches of learning to be
inter-related, so Rhetoric will tend to show that all
knowledge is one.

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote


#+begin_quote
Is the Trivium, then, a sufficient education for life?
Properly taught, I believe that it should be. At the end of
the Dialectic, the children will probably seem to be far
behind their coevals brought up on old-fashioned "modern"
methods, so far as detailed knowledge of specific subjects
is concerned. But after the age of 14 they should be able to
overhaul the others hand over fist. Indeed, I am not at all
sure that a pupil thoroughly proficient in the Trivium would
not be fit to proceed immediately to the university at the
age of 16, thus proving himself the equal of his mediaeval
counterpart, whose precocity astonished us at the beginning
of this discussion.

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote


#+begin_quote
What use is it to pile task on task and prolong the days of
labor, if at the close the chief object is left unattained?
It is not the fault of the teachers--they work only too hard
already. The combined folly of a civilization that has
forgotten its own roots is forcing them to shore up the
tottering weight of an educational structure that is built
upon sand. They are doing for their pupils the work which
the pupils themselves ought to do. For the sole true end of
education is simply this: to teach men how to learn for
themselves; and whatever instruction fails to do this is
effort spent in vain.

-- Dorothy Sayers | The Lost Tools of Learning, 1948
#+end_quote
