#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Introduction to the Trivium
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-introduction.org
  :Created: 2017-02-13T12:32@Prek Leap (11.642600N-104.919210W)
  :ID: 3485b3fc-3c51-4459-847c-462b7a5d040f
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4


* Status of This Document

The latest version of this document is: src_sh[:results value]{git describe --abbrev=0 --tags}

#+HTML: <div class="notice notice-info">
*Changes since the last version*

#+HTML: <ul>

#+BEGIN_SRC sh :exports results :results value html :var TAG="v00.01.02"
  RES='git log $TAG...HEAD --pretty="<li>%s</li>\n" -- (file-name-nondirectory (buffer-file-name))'
  if [ -z $RES ]; then
    RES="<li>no changes</li>"
  fi
  echo $RES
#+END_SRC

#+RESULTS:
#+BEGIN_EXPORT html
<li>no changes</li>
#+END_EXPORT

#+HTML: </ul>
#+HTML: </div>

* Introduction

Keep in mind that this not the Medieval Trivium, though much has been
borrowed from it, including a lot of nomenclature. It would be better
to call this the /Scopic Trivium/.  We will learn more about Scopic
Philosophy later in this introduction.

The Medieval Trivium was the equivilent of a modern College or
University Bachelor's Degree.  And the Medievel Trivium is still the
ancient ancestor of the Liberal Arts Bachelor's degree program, though
one must often squint with just the right amount of grimmace to see it
at times.


---

There is no small amount of tension in the Trivium between
Grammar, Dialectice and Rhetoric.  Each is a very different
way of understanding the world, relating to it,
communicating with each other about it, and figuring out
what it means.

In a way it's amazing that it held together at all, for so
long, with all three splitting in a very messy divorce will
all parties claiming that they keep the children...






* Scopic Philosophy

It was really only recently that I realized that my relentlessly
evolving concept of Scope had become— while I was not watching—a
philosophy in its own right.

Every Civilization is built on philosophical tradtions that contain
many variations over time and location, but like in Jazz
improvisation, still manage to stay within the theme set at the
beginning.  The Western Tradition that Western Civilization is based
on Greek/Roman tradition.  If there is an Eastern Tradition, it could
be argued that it is based originally on Hindu mytholody and was later
refined into Buddhist/Confucian Tradation.   

It is my belief that a new Tradition will need to be established in
order for a truly distributed, /solar civlization/ to be possible that
reflects the fundemental change that mankind is undergoing that is
redefining its relationship to nature and the universe.

This is not to say that Scopic Philosophy will be the foundation for
/anything/, let along the foundation an underpinning Tradition for a
civilizaion, but I do hope that it will be useful for those who do.

** Components

Scopic Philosophy is modular in that it provides a framework for
understanding how the world works.  But it can also be combined with
any number of classical philosophies of life.  It works extremely well
in combination with Skepticism and Epicureanism.

  - Reconciles Atomist and Holistic views of the World.
  - A concept of Time and Causality based on Process Philosophy
  - A Temporal Model based Scope (Context: LOD, POV ROC)
  - A Dynamicly Changing Cosmology that reflects the current scientic consensus
    of how the Universe works based on the scientific method.
  - Plug-in Philosophy of Life
  - Plug-in Phlosophy of lifelong learning.

* Learning -- onion

think of learning as something akin to the human brain which is made
up in successive layers -- with the reptilian brain at the core, and
eventually adding the limbic system and finally the neocortex

It's important that knowledge is taught as if it is an onion that is
builds layer apon layer until reaching the present state of knowledge
at the outside which can then be the basis for building new layers.

Knowing how we have come to know something is important because it
includes all of the blind alleys and walls that we kept running up
against before finally surmounting them to build up the next layer of
the onion.  The history of knowledge is all about how to build better
mousetraps by first knowing all of the past mousetraps that have been
devised in the past, and how they have worked or not....


* Scopic Trivium

can't separate trivium from Latin -- this is important, because we
will be teaching english as a foriegn lanaguage, even to native
speakers -- it will be a very specific language designed to bridge
generations and linguistic drift so that texts will remain in use over
very long time frames.

This will be especially important for scientific papers and cannonical
works -- and translation of older english works into scopic english
will have to be undertaken -- or at the least that editions are
presented that provide glossa and scholia that define anything that
falls outside of Scopic vocabulary and usage. 

This will especially be important for technical terms -- which go in
and out of vogue far more often than might be thought....

The Scopic Trivium this will include:

   - english (a defined subset that will change slower than the
     vernacular)
   - scopic a SDL (domain-specific-language)
   - incantation script (based on CJK)


* Trivium
 

Need to think about the trivium in context with Havelock's idea of
pre-literate modes of thought.  The heavy emphasis in the trivium on
rhetoric as a tool for oratory is solidly grounded in, the spoken word
-- something that we shifted away from in the modern era -- mass
education, and universal literacy shifted the role of oratory
dramatically sometime towards the end of the 70's -- the tipping point
happened and no one seemed to notice.

We are living in a post-oral world -- which oddly coincides with a
post-literate segmentation of society which places less importance on
the written word, and instead gravitates towards produced multi-media
that seems to attempt to bi-pass rationality and logic all together
and appeal directly to the emotions that are adrift in a contextless
cloud that swings often violently between desires and fears.  Not only
is there no context -- there is no stability, shifting sands beneath
out feet.  This condition is well known to those in power, in
government, religion, and industry and are used against us, as a tool
of control, which runs diametrically opposite to the role that human
institutions are supposed to provide.  The culture, layer has been
turned against us -- subverting institutions to make us more afraid,
to make descision that are not in our self interest, and only serve to
enrich an elite who are trapped in their own bubble of desire, fear
and hunger for power and status.  This is why people no longer trust
institutions to provide truth, or justice, or even a living wage.




** Intro
the tools needed to study the quadrivium

  - Grammar  :: symbol systems to communicate and manipulate langauge
    - written language -- tools to express written language - chalk,
      ink and bits.  
    - reading :: 4 kinds
    - etymology :: history & conext of words
    - history :: time as narratives 
      - process philosophy
      - oral, written & code traditions
    - number :: 
    - code :: dynamic manipulation of text (everything is text)
    - maps :: spatial symbol systems
    - bitmaps :: images / video
    - geometry / vectors :: 
    - audio ::    
  - Logic    ::
    - analytical and synoptic reading
  - Rhetoric :: communication
    - composition
    - communication
    
The Trivium should be started at the age of 11, no earlier.  At this
age the child is able to begin to comprehend complex and abstract
concepts.

The Trivium provides the child with the intellectual tools to express
thoughts in spoken, written and code form, communicate with others,
and to think rationally and critically.

These arts will be a foundation that the child will be able use the
rest of their lives and form the basis for self-directed and directed
study in the future.

**** Subjects included

- history
- literature
- 

** Grammar
** Logic
** Rhetoric
