#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Otium
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-otium.org
  :Created: 2017-04-20T10:17@Prek Leap (11.642600N-104.919210W)
  :ID: 55a6372f-54ef-421c-a9d0-ba7a95ff2c3b
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction

#+begin_quote
> I found it irritating that there was inconsistent usage of
> tabs and spaces at the beginning of lines.

When this happens, I recommend to go take a walk, look at
the trees, enjoy life...

-- [[http://mbork.pl/2017-05-17_Some_emacs-devel_humor][Marcin Borkowski: 2017-05-17 Some emacs-devel humor]]
#+end_quote


Beyond the three /subjects/ of the Trivium there is no
practical methodology or philosophy about how to live and
work.  The intellectual tools that the Trivium gives us must
be matched by a daily workflow that is product and
sustainable -- these two concepts are embodied in Mastery
and Otium.

#+begin_quote
Your dull, unhurried worker gets over a great deal of
ground, because he never goes backward or breaks down. Your
intense, convulsive worker breaks down and has bad moods so
often that you never know where be may be when you most need
his help,—he may be having one of his 'bad days.' We say
that so many of our fellow-countrymen collapse, and have to
be sent abroad to rest their nerves, because they work so
hard. I suspect that this is an immense mistake. I suspect
that neither the nature nor the amount of our work is
accountable for the frequency and severity of our
breakdowns, but that their cause lies rather in those absurd
feelings of hurry and having no time, in that breathlessness
and tension, that anxiety of feature and that solicitude for
results, that lack of inner harmony and ease, in short, by
which with us the work is so apt to be accompanied, and from
which a European who should do the same work would nine
times out of ten be free. These perfectly wanton and
unnecessary tricks of inner attitude and outer mariner in
us, caught from the social atmosphere, kept up by tradition,
and idealized by many as the admirable way of life, are the
last straws that break the American camel's back, the final
overflowers of our measure of wear and tear and fatigue.

-- William James, /The Gosple of Relaxation/ 1899
#+end_quote


#+begin_quote
The advice I should give to most teachers would be in the
words of one who is herself an admirable teacher. Prepare
yourself in the subject so well that it shall be always on
tap: then in the class-room trust your spontaneity and fling
away all further care.

-- William James, /The Gosple of Relaxation/ 1899
#+end_quote


#+begin_quote
My advice to students, especially to girl-students, would be
somewhat similar. Just as a bicycle-chain may be too tight,
so may one's carefulness and conscientiousness be so tense
as to hinder the running of one's mind. Take, for example,
periods when there are many successive days of examination
impending. One ounce of good nervous tone in an examination
is worth many pounds of anxious study for it in advance. If
you want really to do your best in an examination, fling
away the book the day before, say to yourself, "I won't
waste another minute on this miserable thing, and I don't
care an iota whether I succeed or not." Say this sincerely,
and feel it; and go out and play, or go to bed and sleep,
and I am sure the results next day will encourage you to use
the method permanently.

-- William James, /The Gosple of Relaxation/ 1899
#+end_quote



* Otium

 - [[http://nautil.us/issue/46/balance/darwin-was-a-slacker-and-you-should-be-too][You Should Work Less Hours—Darwin Did]] | Nautilus
 - [[bib:pang:2016rest][REST: Why You Get More Done When You Work Less]] | Alex Soojung-Kim Pang
 - [[https://www.scientificamerican.com/article/mental-downtime/][Why Your Brain Needs More Downtime]] | Scientific American

 - [[https://www.uky.edu/~eushe2/Pajares/jgospel.html][The Gospel of Relaxation]] | William James
 - Gospel of Relaxation | William James (pdf)
 - Advice for a Young Investigator | Ramón y Cajal
 - Muße und Kult (Leisure: The Basis of Culture) | Josef Pieper
 - Leisure: The Basis of Culture | Josef Pieper 1948

 - [[https://en.wikipedia.org/wiki/Josef_Pieper][Josef Pieper]] | Wikipedia


#+begin_comment
Based on: NOTES <2015-07-24 Fri 12:29> Studyhall About Page

My concept of Otium is now evolving more towards the larger concept of
/rest/ as a counterpart to /practice/ which is at the heart of /mastery/.

#+end_comment


In addressing the deep learning deficiencies that are
inherent in Hacker Culture, it is worth looking at the
complex concept of [[https://en.wikipedia.org/wiki/Otium][otium]].

We use /otium/ in the sense of a period of time spent
retiring from public or daily life for the purpose of quiet
contemplation.  The opposite of otium, /negotium/ is public
life, from which we get the english word /negotiation/.

The concept of otium is the polar opposite of the
hyper-connected always on, always available life online.
Otium is all about assimilation of what has been learned and
experienced, and dedicated to looking for connections and a
deeper understanding of things in a larger context.  Otium
is a time for reading, for writing, for thinking and
sketching.  It is a different kind of work, which is
neccessary to really learning anything.

Sleep is similar, in that it is a time for the brain to make
chemical repairs, but it is also a time for the
sub-conscious to work through problems and make connections
that it couldn't do when awake.

Life connected to the firehose of social media, news cycles,
and a constant barrage on the senses from adversiting,
social and work responsibilities overwhelms and makes it
impossible to see what is really happening, to see the
patterns in the chaos.  It is only when you have time to
make those connections that you turn information into
knowledge and knowledge into wisdom.

Traditional education in small doses, when done right, has
many worthwhile traditions and methodologies but they tend
to be expensive, and time consuming.

Setting aside some time for otium, and deep learning is
preferable to attending traditional training or school
courses because they part of public life, group politics,
peer pressure that are prone to distraction.

The first problem is to weave periods of otium into daily
life.  A few minutes with a cup of coffee, in a quiet place
with the phone in airplane mode.  A long walk at dusk, along
the riverside, working through a problem without
distractions.  The second problem, which is harder than the
first, is how to integrate this concept, how to learn to
shut off the firehose and be comfortable with your thoughts.

* Dealing with increasing Rate of Change

How much of Otium is slowing things down -- to deliberately
not try to take in too much at once?

The arguement then becomes, that if you do that, you will
fall behind.  I am certainly guilty of such beliefs.  But is
it true?   

And if it is true then that is what information tools are
for.  To deal with the deluge for us, and allow us to not
miss was is important that is buried in the sediment without
having to personally go through the whole thing by hand like
panning for gold.

We aren't there yet -- Google has not been that tool.  And
frankly no one seems to even be trying to build such tools.
AI could do it though, by watching what we do, it will
become better and better at finding what we are looking for
-- though perhaps not so good at finding things that are
important that we don't know exist...  and that is the real
challenge here.


* Quotes

#+begin_quote
THE IDEA OF work and rest as opposites and competitors now
seems perfectly logical, but it’s one of those logical ideas
that’s actually a historical artifact. Before the eighteenth
century, the boundaries between work and rest were not so
clear-cut. Workplaces and domestic space were often
intertwined: in the preindustrial era, skilled workers had
shops in their homes, small farmers brought livestock into
the house during winter months, scholars and teachers gave
lessons out of their homes, and apprentices lived with their
masters.

Working time was more flexible and “task-oriented,” as labor
historian E. P. Thompson put it, and many workers sought to
work only long enough to provide for their basic needs. This
order was upended by the Industrial Revolution in the
eighteenth and nineteenth centuries. The factory and office
came to be seen as the places where “real” work
happened. The home, in contrast, evolved into the domestic
sphere, the place where a man could relax and recover from
work. (Of course, men could believe that the home was a
retreat from work so long as they did no work there; for
women it was a different story.) The labor movement’s
advocacy of shorter hours, paid vacation days, and holidays
further (though unintentionally) contributed to a sense that
work and leisure were opposites and could be haggled over
and won and lost.

The template of industrial labor, including its underlying
assumptions about work and rest, was copied by service
industries, professions, and bureaucracies in the
mid-nineteenth century. The modern office was conceptualized
as a machine for rationalizing and organizing intellectual
labor, and it copied the working hours of factories. But the
model has been an imperfect fit in creative industries, as
it’s extremely hard to measure productivity and quality in
creative and knowledge work. In factories and fields, you
can point to tangible products at the end of the day; in
industries where the “product” is intangible and projects
may take years to complete, it’s harder to assess from day
to day how you or your subordinates are performing.

-- REST
#+end_quote

#+begin_quote
According to a 2015 Bureau of Labor Statistics report, in
the United States parents of young children spend an average
of seven hours every workday taking care of
children. Earlier generations gave children more
independence and mobility, but today’s parenting is more
time-and labor-intensive. This is one reason the amount of
time spent on housework has barely budged in the last
hundred years, despite the invention of dishwashers, washing
machines, and other appliances.

-- REST
#+end_quote

#+begin_quote
We also spend more time commuting to work—and the proportion
of people with long commutes is rising, too. In the UK,
according to a 2015 study, roughly 3 million people, or 10
percent of the labor force, spent more than two hours a day
commuting in 2014, a figure that had increased more than 70
percent since 2004. In the United States, workers spent an
average of twenty-one minutes commuting in 1982; by 2014,
that number had climbed to twenty-six minutes, with 17
percent of commuters spending forty-five minutes or more
commuting. (The amount of time commuters spent stuck in
traffic also rose, from sixteen hours a year in 1982 to
forty-two hours a year in 2014.)

-- REST
#+end_quote

#+begin_quote
In ancient and medieval Europe, philosophers argued that the
exercise of pure reason was never sufficient to make sense
of the world. Knowledge (and the culture that formed through
the accumulation of knowledge) required the marriage of
logical and discursive methods (ratio) and contemplative
practices and attitudes (intellectus). Intellectus, in turn,
was enabled by leisure, which Pieper described as not just a
“result of spare time” but “an attitude of non-activity, of
inward calm.” The philosopher’s capacity for insight had its
center in this “tranquil silence” that only the world’s deep
truths could disturb and that provided space for the
cultivation of intellectus. Leisure was, as the English
translation of Muße und Kult put it, the basis of culture.

Modern thinkers and industry destroyed this organic vision,
Pieper argued. Immanuel Kant argued that only active
intellectual effort could serve as a firm basis for
knowledge; as he put it in 1796, “reason acquires its
possessions through work,” and forms of knowledge that claim
anything other than formal, rational foundations are
suspect. Cognition, Pieper wrote, became in the eighteenth
century “an active, discursive labor of the ratio” alone,
and intellectus and leisure were discarded.

-- REST
#+end_quote

#+begin_quote
The medievals distinguished between the intellect as /ratio/
and the intellect as /intellectus/. /Ratio/ is the power of
discursive thought, of searching and re-searching,
abstracting, refining, and concluding [cf.  Latin
/dis-currere/, ”to run to and fro”], whereas /intellectus/
refers to the ability of ”simply looking” (/simplex
intuitus/), to which the truth presents itself as a
landscape presents itself to the eye. The spiritual knowing
power of the human mind, as the ancients understood it, is
really two things in one: /ratio/ and /intellectus/, all
knowing involves both. The path of discursive reasoning is
accompanied and penetrated by the /intellectus/’ untiring
vision, which is not active but passive, or better,
/receptive/ - a receptively operating power of the
intellect.

-- Josef Pieper, /Leisure, The Basis of Culture/ 1948
#+end_quote

