#   -*- mode: org; fill-column: 60 -*-
#+TITLE: Practice
#+STARTUP: showall
#+PROPERTY: filename
  :PROPERTIES:
  :Name: /home/deerpig/proj/chenla/trivium/triv-practice.org
  :Created: 2017-04-20T18:29@Prek Leap (11.642600N-104.919210W)
  :ID: 0dac1b2a-4b7f-461c-a91f-a2e4a89772c1
  :URL:
  :END:
#+INCLUDE: ./inc/head.org
#+INCLUDE: ./inc/macros.org

{{{breadcrumbs}}}

#+HTML: <div class="outline-2" id="meta">
| *Author*  | Brad Collins <brad@chenla.org>             |
| *Date*    | {{{time(%Y-%m-%d %H:%M:%S)}}}              |
#+HTML: </div>

#+TOC: headlines 4

* Introduction



* John Coltrane

Need to track down this story, but I remember reading, on an album
cover for some Coltrane Bluenote album (I think) the the story of when
the author was a young man, learning to play the Sax, having met
Coltrane after a show.  Coltrane asked him if he wanted to practice
with him the next day.  The young man showed up with at the hotel room
the next day and was completely blown away when all Coltrane played
through the entire practice was several hours of scales!  That's it,
no songs or themes or riffs or solos -- just scales...

You could say that scales are for musicians, what a block of marble is
for a sculptor -- they contain all music.
